### ISSUE TITLE
Accessing Current Slide Attributes in onAfterChange after 1.4 update

### ISSUE THREAD

**Issue by heytomsmith** [kenwheeler/slick#1036]
Previous method which was working before the update: 

`console.log($(slide.$slides.get(index)).attr('id'))`

No longer works. Any suggestions as to how I might make this happen? Based on docs, I tried to pull .data() from
`var currentSlide = $('.your-element').slick('slickCurrentSlide');` 
but that didn't work either.

**Comment by simeydotme** [comment]
```js
var cur = $(".slider").slick("slickCurrentSlide");
var $slides = $(".slider").slick("getSlick").$slides;
var id = $slides.eq( cur ).get(0).id;
```

Thanks for contributing, but please provide a jsfiddle in future :smile:

**Comment by heytomsmith** [comment]
Doesn't work. Fiddle: http://jsfiddle.net/fpbgbgrd/

**Comment by kenwheeler** [comment]
Yes. It Does. 

http://jsfiddle.net/3b4kqy9p/

**Comment by heytomsmith** [comment]
@kenwheeler Thanks for taking a look. I'm trying to return data attributes from the current slide though, what you've shown only gives me the current slide as an integer. 

If I try ` $('.get-the-title').text(currentSlide).data('title');`

then that doesn't work.

**Comment by simeydotme** [comment]
@heytomsmith ... the code I gave you should have been enough for you to get this working, which is why the issue was closed :smile: 

http://jsfiddle.net/3b4kqy9p/2/

If you ever find you dont understand something it's perfectly OK to ask for help! :grinning: , but for future reference you should really only be raising tickets on github if you're absolutely certain there's a problem and you can prove it... otherwise please head to stackoverflow.com and ask your questions there, there's thousands of people to help you :)

Simon.

**Comment by heytomsmith** [comment]
Ok thanks, Simon. I'll do that in the future. I'm still learning :sweat:. Thank you both for your help @kenwheeler.
