### ISSUE TITLE
Freeze on Hover

### ISSUE THREAD

**Issue by Ericdowney** [kenwheeler/slick#1100]
The current slider with pauseOnHover enabled will finish its animation before stopping.  I was wondering if it's possible to have the slider completely freeze when the user hovers over. Then when the user moves away have the slider pick up where it left off.

**Comment by ArtbyArjan** [comment]
I wanted almost the same thing, where the slider would automatically continue when the cursor would move away and managed to solve it using `slickPause` and `slickPlay`.

```js
$('.js-slick-slider').hover( function(){
    $(this).slick('slickPause');
}, function(){
    $(this).slick('slickPlay')
});
```

Set `pauseOnHover` to `false`

**Comment by simeydotme** [comment]
It's not currently possible, and it doesn't seem like a scenario that should happen... when exactly does a user want to see half of one slide, and half of another?

**Comment by dragosmocrii** [comment]
@simeydotme I was actually looking for this feature. A good scenario is when slick is used for a continuous carousel set on autoplay (logo slider/news ticker/etc). So when the slider is hovered, it would be nice for the slider to stop so the user can click a link or something. Currently, because the slider does not freeze, you have to chase the slide :)
