### ISSUE TITLE
Custom arrows disappear on breakpoint

### ISSUE THREAD

**Issue by Worstkaes** [kenwheeler/slick#1154]
Hi, 

I'm trying to use custom prev-/next-arrows for my Slick-Slider, but after the breakpoint the mark-up of my buttons disappears. 
Has anyone an idea where am I wrong?

Here my Fiddle for this: https://jsfiddle.net/n15gypLn/12/

**Comment by simeydotme** [comment]
1. Why do you have breakpoint when all the settings are the same?
2. change your code to:
```js
        prevArrow: $('#prev_btn'),
        nextArrow: $('#next_btn'),
```

**Comment by Worstkaes** [comment]
The fiddle was just an example. In my original there are not the same options. So the bug isn't fixed?

**Comment by simeydotme** [comment]
Why are you creating fiddles which don't have the same options you're getting the error with? :confused:  .... also _"So the bug isn't fixed?"_ is a question; why don't you check for yourself? -- I don't know if your project is OK or not :wink: :joy:

**Comment by Worstkaes** [comment]
Better I don't use the words I usually would say to people like you. Why do I have to use the same settings, when the bug exists in the fiddle too? Isn't this enough? *funny_face* *haha*

**Comment by simeydotme** [comment]
>Why do I have to use the same settings, when the bug exists in the fiddle too? Isn't this enough?

You don't have to use the same settings; _but I can't properly help you without them_ :)
If you care to check the code I provided; I think you'd find it works. And if it doesn't then you better provide a proper fiddle so we can investigate and fix the issue in the Slick source for you :)

--[edit] Oh You've changed your second comment which muddies the water in regards to my response and it's tone :stuck_out_tongue_winking_eye:  - but regardless; because I was jesting that without a proper fiddle I cannot guess if your project works now or not ;)

I'm glad your issue is fixed and sorry you have distaste in your mouth when I try to help you.

Simon.

**Comment by Worstkaes** [comment]
I edited my second comment before your answer. 
The fiddle showed the error and thats all you needed for debugging. If you need the next time my personal touch, I will add my options for you. 
Your code was helpful, your jabbering wasn't.

**Comment by devonmather** [comment]
Same issue here, using jQuery object as suggested above instead of a string fixes the issue, however the documentation states a string is an acceptable argument to pass.
