### ISSUE TITLE
Firefox slick-dots not vertically aligned

### ISSUE THREAD

**Issue by modivinit** [kenwheeler/slick#1177]
Hi folks:

Just want to confirm if this is a settings issue or a known/new issue. In Firefox only I am seeing that the dots are not vertically aligned in-between the arrows. 

![screen shot 2015-03-24 at 10 25 27 am](https://cloud.githubusercontent.com/assets/3927853/6808265/575cc568-d210-11e4-889b-67c4202fc2c4.png)

Renders great in Chrome and Safari. Appreciate any guidance!
Thanks!

**Comment by simeydotme** [comment]
I think this is due to Firefox having `whacked-up-as-fuck` font-sizing on icon fonts, I don't know of this issue myself (please provide a fiddle) but I have issues in Firefox all the time with icon fonts not aligning properly.

If you provide a demo; others can try to solve the issue... a screenshot of your custom CSS does not show a bug in Slick ;)

Simon.

**Comment by modivinit** [comment]
Thanks Simon! Sorry for the delay and agree a screenshot doesn't mean anything. Next time will post with a fiddle!  

Let me close this issue and re-open again, if needed, once we have tried a few things. 

-Vinit
