### ISSUE TITLE
Responsive breakpoints break angular bindings

### ISSUE THREAD

**Issue by Preece** [kenwheeler/slick#1227]
When a responsive breakpoint is hit, and the carousel reconfigures to have a different number of slides, angular bindings such as ng-click break. I believe this is because internally the carousel manipulates the DOM and that does not play well with angular.

**Comment by JarredMack** [comment]
I'm having the same issue with standard JS bindings. I have elements in a carousel which have click events bound - these appear to be getting wiped when applying the responsive property to the carousel initialisation.

Pen demonstrating the issue here - the responsive carousel overwrites click bindings:

http://codepen.io/JarredMack/pen/dPxVZg

I would imagine this has something to do with cloning the slide content for the responsive slides, but I haven't dug into the library yet.

**Comment by JarredMack** [comment]
The same issue occurs with standard JS click events - see the following pen for an example (drag window in to trigger responsive callback): 

http://codepen.io/JarredMack/pen/dPxVZg

This is because in order to apply the responsive properties, slick is destroying itself and reinitialising in the refresh() method. Obviously, this blasts any bindings attached to the DOM and gives you fresh, unbound DOM content for your carousel.

**Comment by JarredMack** [comment]
Out of curiosity, I replaced `_.refresh()` with `_.unfilterSlides()`, which does largely the same thing without  destroying the existing carousel instance. The carousel correctly reapplied the responsive styles at each breakpoint, without clearing the DOM bindings due to reinjecting the content.

As `_.refresh()` is currently only called as part of the `checkResponsive` method, is it possible to have it reimplemented similarly to `unfilterSlides`? I don't see any reason it needs to destroy itself on screen resize.

**Comment by coldes** [comment]
excellent fix  - was tearing my hair out with this one - thank you - fyi my new working scenario

	$('.newsmenu').on('init', function(event, slick) {
    	slick.refresh = slick.unfilterSlides;
	}).slick({
        infinite: false,
        speed: 1300,
        slidesToShow: 3,
        slidesToScroll: 1,
        arrows: true,
        responsive: [{
            breakpoint: 480,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 1
            }
        }]
    });

**Comment by kenwheeler** [comment]
Fixed, thanks

**Comment by amrfaisal** [comment]
Check my answer for Angular use-case:
http://stackoverflow.com/questions/29101254/angularjs-slick-js-carousel-ng-click-not-firing-with-responsive-attribute-settin/30584787#30584787
