### ISSUE TITLE
nested slick destroy after parent slick fire breakpoint

### ISSUE THREAD

**Issue by matiaspub** [kenwheeler/slick#1230]
Thanx so much for work!

But I have problem with nested slick's.

When my parent slick reaches first breakpoint, children(nested) slick's will be destroyed and sliding stops working.

**Comment by leggomuhgreggo** [comment]
Hey, man, interesting issue!

Real quick: juboi Ken Wheeler has kindly asked that issues be accompanied by a fiddle so that anyone troubleshooting can see the problem without having to guess at recreating it under an uncertain set of variables.

I was curious though so I [made an example for you](http://codepen.io/gwst/pen/vEoNyO) AND I think I found a work around, by adding responsive breakpoints on the child slick as well. Only drag is that it reshuffles the slides at the breakpoints. but you could set speed to 0 to make that less of an issue, at least visually.

There are a couple other issues that are sort of related to this one, so I wouldn't be surprised if this functionality evolves.

Cheers!

**Comment by matiaspub** [comment]
Thanx so much.
It really simple and logical)
