### ISSUE TITLE
Would like slidesToShow to be less rigid when combined with variableWidth: true

### ISSUE THREAD

**Issue by mkstix6** [kenwheeler/slick#1377]
I have a slick slider i'm using as a nav for a gallery. So the slick slider is showing many items around 8 and 15 ish. You can click on one to see it larger.
The images in the gallery have variable resolutions and ratios. Also a mixture of portrait and landscape images. I have the images all set to the same height, So i'm using variableWidth: true as i don't want large gaps between them. 

When slides are variable width and a page is responsive it is next to impossible for me to put an integer value to the number of slides that will fit in the visible track.

If i set a low number the arrows and touch events are always present even if there aren't enough images in the gallery to fill the track.

If i set a high number the arrows won't alway appear as the track overflows.

I'd really like to use a slidesToShow: auto option, or something to this effect, that calculates whether the slides are overflowing the track. If the items overflow the control arrows and touch events are activated.

Would need to evaluate after image load complete and on window resize.

**Comment by shahafabileah** [comment]
+1 on having `slidesToShow: auto`.

Instead of specifying the number of slides to show, I'd love it if I could specify the amount of margin between slides: `marginBetweenSlides: '15px'`.  Slick should then be able to determine whether there's overflow or not.

The nice thing about this setup is that there would be no "page pop" when the page first loads.  My own CSS can specify that slides need to be 15px apart.  When the $.slick code runs, it will maintain the same amount of margin.  So, nothing will shift.  The slides will simply become draggable.

**Comment by devonmather** [comment]
Yes, it would be nice to have this, maybe slightly diverging from what's been said but also an easy way to set slidesToScroll to scroll to the next element that is not slick-active, without a slidesToShow: auto setting and variable widths this has been difficult to implement.

**Comment by marcorieser** [comment]
Yes, please :+1:

**Comment by kenwheeler** [comment]
So with the current layout setup, this is prohibitively difficult to do, but I'm working on a refactor for 2.0 where this will be easy

**Comment by mkstix6** [comment]
Awesome! Thanks.

**Comment by marvinhagemeister** [comment]
+1 In the last 3 projects at work I'll hit this issue as well. I've just peaked into the 2.0 branch. Any news on update or what is needed to get it released? I'd love to help out

**Comment by mkstix6** [comment]
Woo. I'm assuming closed + 2.0: Considering is a good thing for this feature. Thanks :).
