### ISSUE TITLE
Ist there a possibility to have truncated slider only on the right side like on amazon.com

### ISSUE THREAD

**Issue by mj-neusta** [kenwheeler/slick#1409]
Like the centered version but only truncated on the right side and justified on the left.

**Comment by shahafabileah** [comment]
I'm trying to do the same.  So far I found that this approach kinda works:

```
        $(this).slick({
            slidesToShow: 5.5
        });
```

For this to work you have to know the width of your slides and the width of your container, to make sure that there's enough room for 5.5 slides to show with padding between them (and no overlap).

**Comment by shahafabileah** [comment]
One issue I discovered with the "partial slide" solution I proposed earlier is that if you dynamically add new elements to the list using ajax, then after each add-item action, slick will adjust the "scroll position" of the carousel so as to be at the start of a slide.  This makes for a jarring experience -- the slides all suddenly shift to the left by 50%.

This issue is also discussed here: https://github.com/kenwheeler/slick/issues/1299
