### ISSUE TITLE
Full-width Hero Slideshow Bug

### ISSUE THREAD

**Issue by cbaone** [kenwheeler/slick#1418]
Slick is great, but I'm having an issue using it on a full-width, responsive hero. I'm using background-cover for the hero images. The slides (originals, not cloned) resize just fine if the content differs within them and when window is re-sized, but when it gets to a cloned slide it slides in then resizes. So, I'm getting that half second while the slide adjusts and it's downright ugly. I want infinite set to true. If I disable it then the problem goes away along with the benefit I was looking for. 

Here's a gif of what's happening. I just barely ran into the problem and creating a fiddle for it right now is going to be tough, but I'll work on getting one posted. If anything stands out as obvious don't be afraid to point it out :) Thanks.

Here's a fiddle demonstrating the issue: https://jsfiddle.net/cbaone/ofd70d0n/2/ cycle through the slides until you hit the first slide again and it resizes on animation. No bueno.

![hero](https://cloud.githubusercontent.com/assets/239041/7988461/d020dbce-0aa0-11e5-9411-b44922c578f4.gif)

**Comment by gausarts** [comment]
I think the underlying issue is more with the same ID (#hero-title) applied for multiple items, since the cloned slides IDs will  be stripped by Slick:
https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L2027

And it is also not correct to have multiple similar IDs on a single page
I set up the corrected version using class (.hero__title), and it behaves correctly:
https://jsfiddle.net/ofd70d0n/5/

**Comment by cbaone** [comment]
You may be right. That would be an embarrassing oversight of mine if that's the case. I actually moved on from slick for the time being, but will check it out to see if that was the problem. Thanks for checking it out.
