### ISSUE TITLE
IE9 Multiple Sliders

### ISSUE THREAD

**Issue by Coderra** [kenwheeler/slick#1428]
I am using Slick on a dev site and in 2 sections there are 2 sliders on the page. They work flawlessly on all modern browsers, but when I go into IE9 and the first gen ipad, only the first slider on the page is rendered as a slider. The other one throws up an error and stacks all the images one on top of the other.

'Object does not support this property or method - slick.js'
line 1167.

I commented out a few of the lines around there which are settings for pause on hover and autoplay. But the error just keeps moving up! Any ideas?

I'm not sure whether this is just me or not. But the dev site is here - http://dev.gainsboroughschool.co.uk

**Comment by nominalaeon** [comment]
I just had a similar issue in IE8. I was using the imagesLoaded library to make sure Slick didn't fire until the images were on the page giving their containers the appropriate heights.

Unfortunately IE8 only loads in like 6 or 8 things at a time (scripts, images, other documents, etc) and if that page load time takes longer than some arbitrary number Microsoft set (50 seconds or something) then it times out. That timeout kills the JavaScript processes but still loads in all of the rest of the page stuff, so the the images load up, but they're all stacked.

I didn't investigate too closely, but it looks like you've got a couple of $(window).load functions declared. If those functions are holding up the rest of the JavaScript, this could be the issue you're facing. Try running everything with $(document).ready instead, that *might* do the trick.

A way to test what I'm talking about is to open the Network tab and refresh the page. Some things will show that they took like 30 seconds to load! It's not because they took 30 seconds though, it's because they waited 29 seconds to queue up and then load on the page. The Network tab's timeline will illustrate what I mean.

I might be way off base, but that wound up being my issue. I had to find a work around for resizing variably heighted containers after the page loaded and Slick init'ed.

If you load up Modernizr, you'll get the "ie8" and "ie9" classes added to <html> which help isolate this janky work-around in your JS ...among other benefits.

**Comment by Coderra** [comment]
Many thanks for your reply and taking a look. I'm not very proficient with JS yet, but I removed the two window load functions and still got the same so have put them back. On the homepage I've not optimised the slides yet so that will slow it down a little, but if you look on this page: http://dev.gainsboroughschool.co.uk/the-reception/

You see that the same thing happens in IE9 where having 2 sliders on one page breaks the staff slider and the gallery under it is OK. The strange thing is when I flip the calls for the sliders around in the footer, so declare the staff slider as the first slider on that page and the gallery as the second, the problem reverses. I.e. that the gallery breaks and the staff slider is OK. I'm not sure it is a load time issue as the images on these pages are already quite small and the server is quite quick.

**Comment by nominalaeon** [comment]
I can't get it to break in IE9 or even 8. Did you wind up finding a fix?

**Comment by Coderra** [comment]
That's strange. It's all the same as it was. The only thing I've done is optimised the images for the galleries. Looking at the home page I still get 1 working slider in the header and then the 'Lorem ipsum' below welcome to the school is supposed to be a slider of recent important snippets and that doesn't work. Same with on the year group sections. The staff one breaks and stacks the staff images one on top of the other while the normal gallery works fine. It's just really strange. 

I'm wondering whether there is something wrong with the scripts i'm using for the sliders. I say this because the one called first on the page works fine, and the one called last breaks. But I can't see anything that would do this and since all of them are replicas of each other with a different class they should work fine.

**Comment by nominalaeon** [comment]
I really think it's IE9 timing out the JavaScript. Maybe my connection's faster so the images load in before the timeout or something. I dunno, I'd look closer if I could duplicate.

**Comment by Coderra** [comment]
Perhaps, but the browser doesn't seem to make any effort to turn this into a slider. It could be timing out. Is there any work around for that? I know I could lazy load the images but with how it is it's like it loads the first one and then says, 'right that's me done!'. it's the same on the first generation ipad. So I worry the lazy load won't make much difference.

**Comment by kenwheeler** [comment]
Not sure whats going on here. If you can reproduce isolated in a jsfiddle, I'll reopen.
