### ISSUE TITLE
Slick Only Works on Initial Page for jQuery Mobile

### ISSUE THREAD

**Issue by cardguy1000** [kenwheeler/slick#1430]
When using jQuery mobile slick only works when on the first page if a margin is specified for slick-slide

In this fiddle it loads because it's on page 1
http://jsfiddle.net/2kxrfkz2/1/

In this fiddle, click "Go to Page 2" and notice it doesn't work.
http://jsfiddle.net/2kxrfkz2/2/

**Comment by saunders1989** [comment]
I know this is tricky to do in a fiddle because when you add external resources it adds it to the head.

if you read this - http://demos.jquerymobile.com/1.3.2/faq/scripts-and-styles-not-loading.html

it explains that adding scripts to the head will only load once because it is fetching the next page via ajax and only replacing the content.  if you add the scripts to the bottom of the body does it still have a problem?

**Comment by cardguy1000** [comment]
I tried removing <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.5.0/slick.min.js"></script> from the head and adding it to the end of the body with the same result.

**Comment by saunders1989** [comment]
I have changed your fiddle slightly to run on the pageshow function that jquery mobile uses:
http://jsfiddle.net/2kxrfkz2/4/

The reason it does not work how you expect is explained quite well here - http://www.gajotres.net/how-jquery-mobile-page-handling-affects-javascript-executions/

**Comment by cardguy1000** [comment]
Thank you so much.  I have been toying with this for days.  I tried pageinit, pagecreate, pagebeforeshow just about everything but pageshow.  I really appreciate your help.

**Comment by saunders1989** [comment]
No problem... Glad I could help
