### ISSUE TITLE
Problems with the "Last" part

### ISSUE THREAD

**Issue by srcspider** [kenwheeler/slick#1521]
* you require jquery; many developers can do everything with out it so even outside some more complicated interfaces requiring jquery is like asking "please quadruple your javascript size for me"
 * you don't integrate or provide a way to interface with SPA style pages

**On the last point, since it's a bit complicated...**

One of the biggest issues with jQuery and why a lot of modern practices just plain don't use it is that if you're doing anything that looks like a SPA (since the rabbit hole is far deeper then just SPAs) jQuery  can be a real pain due to how at their core many things built with jquery are based on the notion you can fiddle with the dom or that the page will reload and clean the mess they made.

In SPA oriented styles like using React, etc, (but even things like Backbone which is very much jQuery esque) the pattern is different, you want your "component" (which is however the view system defines it for the poison of your choice) to be able to have easy access to it's internal logic and rendering split into an extensible/replacable model that each system can easily replace to suit their needs. In the case of backbone, a template, in the case of React a `<Slick.Carousel />` component, etc.

**Lastly...**

This,

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.5.6/slick-theme.css"/>

Not so cool. Ironically the resource in question isnt even accessible as I write this, as if you prove the point. 

Embed the style information into the javascript, split into some skeleton style that just gives everything structure and a theme that makes everything pretty; allow both to be turned off completely and provide some documentation on what classes are used for styling and what the structure can be so that people can just style it from scratch for their purposes... because they will want to anyway. Having them overwrite your css is just a plain. On that note, the theme information (outside the skeleton structure) should just be a separate component on something like npm so as to not bloat the package when bundling.

**Comment by kenwheeler** [comment]
Do you go leave whiny comments on every jQuery plugin's issue tracker? Is there any jQuery plugin that you are aware of that provides "internal logic and rendering split into an extensible/replacable model that each system can easily replace to suit their needs" for use with whichever SPA framework you drop it into?

So, on to your wildly invalid points:

1. If you don't like jQuery, don't use it. Are you being forced to use Slick by someone? Quadruple your javascript? The jQuery the page would load is most likely already cached if you use a CDN, and if you didn't use jQuery, you'd end up writing a util lib thats almost just as big and 75% less stable. You mean to tell me that you can home roll a util library with the kind of stability, testing and handling of edge cases that it took some of the worlds best js coders years to hone?

2. I work with the second biggest company in the world and they don't have any problem using Slick with Backbone. Further, if you are using React, the only lib where you would really have trouble with DOM fiddling, there's alway this: https://github.com/kenwheeler/nuka-carousel and this: https://github.com/akiran/react-slick
 
Lastly: What is this a joke? I pushed 1.5.6 out an hour ago, it takes time for the CDN to reconcile versions. It's live now. So wait:

You want me to embed the styles into the javascript? You want me to embed the styles of a jQuery plugin into the javascript? 

You are positing that adding an OPTIONAL theme.css, is "bloating" a bundled package. And you think that putting those styles in the javascript won't override your existing CSS?

You see, I already have split the styles into skeleton and base theme. Both are optional. If you are properly bundling your applications with something like webpack, unless you explicitly include those css files, they won't end up in the main bundle. Further, a lot of people like to use it as a starting point. That's why I include a .scss version as well. 

On what planet is it not cool to provide an optional base theme for our less style capable peers?

Don't come here and mouth off to me about jQuery or React. You don't know what you're talking about.

**Comment by kenwheeler** [comment]
For the record, I dropped my finger onto the trackpad to hit the close issue button from about 2 feet above it and made crashing plane noises on the way down.

**Comment by simeydotme** [comment]
:+1: +1 ... I found the responsible code on `line 1` of the `slick.js` file:
```js
lolzTrollMyUsers = require("jquery");
``` 

plz fix immediately.
