### ISSUE TITLE
On mobile/touch - horizontal scrolling should be locked when page is scrolling vertically

### ISSUE THREAD

**Issue by ryanhovland** [kenwheeler/slick#1543]
On mobile/touch devices only:

Currently, if you're interacting with the carousel and swiping horizontally, the vertical scroll of the page is locked; This is good. Similarly, if you click on the carousel and start swiping upwards to scroll the page, the carousel should not be able to swipe horizontally. Otherwise the carousel starts sliding all around and appears squirrely during regular webpage scrolling.

**Comment by chwat** [comment]
+1

**Comment by rglazebrook** [comment]
+1. Has anyone found a workaround for this yet? I have a client requesting their carousel-heavy homepage stop being so "wiggly" on mobile while scrolling vertically. I was hoping touchThreshold was the key, but no luck.

**Comment by leggomuhgreggo** [comment]
Hey, sorry there's been such a long time without this getting attention. I'm going to close this because there is no test case, [per the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you make one we can look at reopening. Thanks!

**Comment by chwat** [comment]
I'll take a peek but had to actually position an element 1px horizontally in order to overcome this issue. This was for a product slider we have on the ThinkGeek.com homepage.

This bug has annoyed me for a long time and have yet to find a solution.  And the 1px overflow is only visible on a non-retina screen.

**Comment by leggomuhgreggo** [comment]
Might have also encountered this. I'll be interested it you can recreate :)

**Comment by sipy** [comment]
+1
