### ISSUE TITLE
Autoplay ScrollTo

### ISSUE THREAD

**Issue by elalemanyo** [kenwheeler/slick#1547]
Hi,

I am having some strange behavior,  when I use the autoplay the page is scrolling all the time to the slider, is this normal? Is there any setting to change this?

Thanks!

**Comment by leggomuhgreggo** [comment]
Hey, sorry there's been such a long time without this getting attention. I'm going to close this because there is no test case, [per the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you make one we can look at reopening.

If you turn include accessibility: false that should stop that behavior. Essentially every time there's a slide change a tab focus event is triggered, which causes this

Hope that helps.
