### ISSUE TITLE
Sliders don't work/sync when centerMode is set to true

### ISSUE THREAD

**Issue by CosmaTrix** [kenwheeler/slick#1549]
Hello,

I'm developing a gallery slider with two synced sliders: one for the photos and one for the thumbnails. The thumbnails slider centerMode is set to true, but when there are less slides than the slides to show this carousel don't work anymore.

As you can see in the attachment the third picture should be centered in the thumbnails slider. The forth picture is not even accessible because the thumbnails sliders doesn't slide at all. That is happening because there are four images in my example and so they fit in the slider's container.

![screen shot 2015-07-20 at 14 39 38](https://cloud.githubusercontent.com/assets/3206387/8775919/33c67d44-2eed-11e5-89a7-9c5fd3884366.png)

Thanks

**Comment by leggomuhgreggo** [comment]
Hey, sorry there's been such a long time without this getting attention. I'm going to close this because there is no test case, [per the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you make one we can look at reopening. Thanks
