### ISSUE TITLE
Using Cutout Images in Slides

### ISSUE THREAD

**Issue by binaryben1010** [kenwheeler/slick#1560]
We use cutout images(transparent background) occasionally in slides and set slick to fade. When we updated slick to version 1.5.0 the cross fade had been changed to just fade in the current slide and NOT fade out the old slide, this gave a nasty sudden disappearance of the old slide. This we noticed had been corrected in version 1.5.6.  Can you make sure all future releases allow for cutout images, even if you require us to set a new config property to enable it.

jsfiddle:  http://jsfiddle.net/binaryben/1wtxb3cr/

**Comment by binaryben1010** [comment]
I have added jsfiddle as requested.     http://jsfiddle.net/binaryben/1wtxb3cr/

**Comment by simeydotme** [comment]
I appreciate the frustration,  @binaryben1010 with the bug that was introduced and then fixed... #thatsOpenSource #DealWithIt

Closing as it's no longer an issue, apparently, it's now a "complaint"

When dealing with 'free' and 'open source' software; things are bound to get missed or broken (little secret, they do in premium software, too), which is why we have an issue tracker. we are maintaining this in our own time and with our own money. we are just humans and theres a million options for Slick. But the awesome thing with open source is you can help us fix the issues, and not just complain about them. 

Thanks for contributing,
Si.

**Comment by simeydotme** [comment]
Also you dont need a carousel to fade images one by one.
