### ISSUE TITLE
Cannot resize carousel slides in a flexbox layout.

### ISSUE THREAD

**Issue by vaidehichhajer** [kenwheeler/slick#1639]
I am trying to get slick carousel working with the flexbox, which has a footer. even thought the slick carousel covers 100% of the remaining space there is no way to make the height of each slide span the whole height assigned to the carousel. Using height: 100% doesn't work.

Any ideas?
My fiddle is here https://jsfiddle.net/qxkqzjow/7/

**Comment by torfranz** [comment]
I had the very same question today and finally got it resolved by listening to the window resize event and setting there the height of '.slick-slide' to the available height within the container.

**Comment by pmeissner** [comment]
How about using calc and vh units? Subtract the height of your footer from the height of the viewport.
```
.carousel__item {
    height: calc(100vh - 100px);
}
```
IE9+

**Comment by vaidehichhajer** [comment]
My footer is variable in height, based on how much text goes in it. torfranz@ Can you elaborate your solution?

**Comment by torfranz** [comment]
I guess you already managed with your flex approach to get the .slick-slider to occupy the available height. But the .slick-slide will keep their initial height which is probably based on the content.
If I guessed this to be correct you could listen to (please ignore any syntax issues, I usually use TypeScript)

$(window).resize(function () { 
     $(.slick-slide).height($("<your container element containing the slick>").innerHeight()) });

In addition you need to make this height setting once at start when the page is shown, otherwise only after the first window resize the height is modified.

**Comment by jdmagic21** [comment]
@pmeissner I was not able to get your solution to work with this. Sorry.
