### ISSUE TITLE
Swipe not working with iframe slide. How fixed?

### ISSUE THREAD

**Issue by Vervinsky** [kenwheeler/slick#1668]
<div class="js-slider" data-items="1" data-dots="true" data-arrows="true" data-mobile-arrows="false">
					<div class="video">
						<div id="slide" class="video__wrapper">
							<iframe class="video__iframe-vimeo" src="//player.vimeo.com/video/108117" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
						</div>
					</div>
                    <div class="video">
						<div id="slide" class="video__wrapper">
							<iframe class="video__iframe-vimeo" src="//player.vimeo.com/video/108117" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
						</div>
					</div>
                   <div class="video">
						<div id="slide" class="video__wrapper">
							<iframe class="video__iframe-vimeo" src="//player.vimeo.com/video/108117" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
						</div>
					</div>
				</div>

**Comment by lolmako** [comment]
It might be because it's the nature of an iframe; when you try to swipe you are selecting inside the iFrame  not where slick actually lives. What you might be able to do is put an overlaying div that's transparent prevent the user from clicking on the iframe, which might allow them to swipe properly. But this will disable the functionality of the vimeo player since you will not be able to click into it.

A possible better solution would be to embed the vimeo video instead of using an iframe.

**Comment by odie2** [comment]
Alternatively just add arrows or dots.
I added arrows for youtube iframes.

**Comment by kenwheeler** [comment]
Indeed, the iframe captures the event.

**Comment by mattLummus** [comment]
For anyone coming across this, the transparent overlay worked for me and can be done via pure CSS. Just add this snippet that targets the element that contains your iframe:

`  
.iframe-container-div::after {
    content: "";
    background: transparent;
    width: 100%;
    height: 100%;
    min-height: 1px;
    position: absolute;
    top: 0;
}
`

**Comment by bhar4t** [comment]
@mattLummus does all functionality inside `iframe` of website working?

**Comment by mattLummus** [comment]
@bhar4t Its been a little while since I initially commented but if I recall correctly, probably not since the overlay would receive any click events (this may vary by browser version). If you need to access controls inside of the iFrame you may have to get creative.

In our case, we had a custom "Play" button in the overlay and re-launched the iframe in a lightbox after a click event. 

So we only needed to handle click events on the slide to launch the lightbox (which would have the full controls) and then any swipe/drag/etc events would operate as normal on the slider.

**Comment by mdfaizanahmed786** [comment]
> For anyone coming across this, the transparent overlay worked for me and can be done via pure CSS. Just add this snippet that targets the element that contains your iframe:
> 
> ` .iframe-container-div::after { content: ""; background: transparent; width: 100%; height: 100%; min-height: 1px; position: absolute; top: 0; }`
> 
> The only catch is that it will prevent other events from triggering inside the iframe by default

This actually works! for those who want to do in react add:
###  In your component
 <div className='iframe-container-div h-full w-full'>
                  <iframe
                  allowFullScreen
                  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                  className="h-full w-full object-cover "
                  src="https://www.youtube.com/embed/VY-QKe19p0Y"
                />

### In your root CSS file:
.iframe-container-div::after { content: ""; background: transparent; width: 100%; height: 100%; min-height: 1px; position: absolute; top: 0; }

**Comment by xerosanyam** [comment]
if you have control over iframe code, a solution can be to listen on pointer events inside iframe and send message to parent window. that way links inside iframe will work also work. using this in production, working cool.

**Comment by Siskinbird** [comment]
> For anyone coming across this, the transparent overlay worked for me and can be done via pure CSS. Just add this snippet that targets the element that contains your iframe:
> 
> ` .iframe-container-div::after { content: ""; background: transparent; width: 100%; height: 100%; min-height: 1px; position: absolute; top: 0; }`
> 
> The only catch is that it will prevent other events from triggering inside the iframe by default

God bless you!

**Comment by iriasuarez** [comment]
.iframe-container-div::after { 
    content: ""; 
    background: transparent; 
    width: 90%; 
    height: 100%; 
    min-height: 1px; 
    position: absolute; 
    top: -30px;
    right: 26px 
  } 
This allow me to click the video functions I'm using a Vimeo 
<img width="373" alt="Screenshot 2024-03-13 at 11 30 37" src="https://github.com/kenwheeler/slick/assets/71896179/728d7160-bda8-4c55-886d-afdd770e515f">
 (test by adding background: red)
