### ISSUE TITLE
slickNext (or previous) won't fire before transition is complete...

### ISSUE THREAD

**Issue by fusse** [kenwheeler/slick#1737]
Got a complaint from a client today that the slider doesn't work.

Turns out, the issue is that the slider won't advance to the next slide until the previous slide has fully changed. This becomes very obvious when using long slow transitions. In this case transition is two seconds... In that time customer manages to click on next arrow multiple times and complain that the slider doesn't work.

Try it: http://jsfiddle.net/4sktLkbg/2/ - try to advance to the next slide while the fade animation is still going. Doesn't happen...

Is this a bug or a "feature"? Cause I sure would like to make it possible to advance on click whenever. Even if the fade is cut and the next image is displayed in full.

**Comment by kenwheeler** [comment]
set options.waitForAnimate to false

**Comment by fusse** [comment]
Thank you so much for replying. The reason I missed this option is that I was reading the docs here:
http://kenwheeler.github.io/slick/ - waitForAnimate is not there. But it's here: https://github.com/kenwheeler/slick that I didn't think to read as thought these would match...

**Comment by constantin-iliescu** [comment]
Hello,

I'm trying control the carousel with a jquery ui slider. waitForAnimate makes this reach the correct slide, but still, when you call the goTo method again, right before the animation completes, the slider kind of "jumps" directly to the new index instead of smoothly animating it.

Can you have a look here, please? 
http://codepen.io/anon/pen/qOXjRK

Thank you.
