### ISSUE TITLE
Cancel slide in beforeChange callback

### ISSUE THREAD

**Issue by lbineau** [kenwheeler/slick#1764]
Hi,

This carousel is one of the best but in my opinion it lacks some hooks to control the slider.
For example I would want to cancel/delay the slide to change in the beforeChange callback.
```javascript
$('.mycarousel').on('beforeChange', function(event, slick, currentSlide, nextSlide){
  event.preventDefault();
  TweenMax.to($('.title', currentSlide), 1, {opacity: 0, onComplete: triggerSlideChange});
});
```
Anyone knows how to do that, or is it easy to implement ?
Thanks.

**Comment by leggomuhgreggo** [comment]
Hey I'm gonna close this [because there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) and it's a support request, but there are implementations where the next/prev functions were disabled until a condition was met, which sounds like it might be what you're talking about? Let me know if you want more details.

**Comment by lbineau** [comment]
Hi,
Thanks for the anwser.
Yes it is a support request not a bug. The idea is to let the developer hook the transition to animate stuff inside the slide and let the carousel knows that it can continue the transition.

**Comment by leggomuhgreggo** [comment]
You could manually change slides using the slickNext/slickPrev methods or you could see if you could get the timing proper with CSS animations--[here's a cool example of the latter](http://codepen.io/EngCode/pen/PPJQER/?editors=010)
