### ISSUE TITLE
Wrong width of the slides with margins

### ISSUE THREAD

**Issue by petrovnn** [kenwheeler/slick#1789]
i use slick slider with this option:
```javascript
$("#bottom").slick({
    slidesToShow:9
});
```
but after a window resize slides not always fit the size of the viewing area. Because the width of the slides is calculated at integer pixels (no decimal pixels)

![](http://i.imgur.com/4ejx97a.png)

Here video showing the problem:
https://youtu.be/GtzLp884iA0

and jsfiddle:
http://jsfiddle.net/petrovnn/q017v9sr/6/

on production site: 
http://russian-ice-spb.ru/en/sculptura/ledyanoy-vertep-gpushkin-2013

How can I fix this problem?
Maybe need to use the width of the slides in percentage?
Using CSS did not able to correctly display the slides width in percentage.

**Comment by leggomuhgreggo** [comment]
Margins are tricky when it comes to width calculations. You'll have better luck with padding on the slide and nested divs. [Here's a code pen](http://codepen.io/leggomuhgreggo/pen/obpebv?editors=010) illustrating what I mean. I'm going to close it because it's not really a bug with the slider. Thanks @petrovnn
