### ISSUE TITLE
CSS Scroll Snap Points Enhancement

### ISSUE THREAD

**Issue by Rendez** [kenwheeler/slick#1797]
Hi,

CSS Snap Points just landed on Safari 9. Firefox supports it since version 39 and seems to be landing in the near future in Chrome, as it's part of Canary already. If you haven't seen it yet, check out this Pen:

http://codepen.io/Guilh/full/KpeNJj/

For browsers supporting it, this would allow us to drop the animation handling in `animateSlide()` and `applyTransition()` to a mere `scrollLeft/scrollTop` value setting. The construction of the rail track would simplify to a container with `overflow: hidden` and the scroll bar hidden by oversizing the container just enough. It would also allow us to drop touch events.

Although slick is very optimized, it will never beat a native, hardware-accelerated feature. Let alone, the DOM construction/initialization of the a slider takes a toll on slower mobile devices, which would greatly benefit from an improvement based on CSS touch points.

Thoughts? I would like to hear from the main contribs how feasible is to include this feature within `slick` itself. I would consider starting a branch on this if enough people seem to like the idea :)

**Comment by kenwheeler** [comment]
This feature, much like most of what browser vendors offer today, seems awfully half assed. I'd wager to say that at some point of diminishing return, Slick would in fact beat them them in performance, much like JS animation beats CSS transitions at scale.

As of right now, they do not offer any way to adjust speed or easing, mouse drag doesn't work, and I don't see a clear API in regards to accessing positions via Javascript, or event callbacks when a snap is hit or anything like that. This is based upon some brief research, could be wrong.  

Most of the time wasted initializing the slider is due to using unoptimized imagery. The actual initialization takes like 60ms. The rest is image load times, which would affect this browser feature as well.

**Comment by Rendez** [comment]
I see all your points, and I agree as you seem to have dug into it way more than me. Just one question since you mentioned it:

> Most of the time wasted initializing the slider is due to using unoptimized imagery

What do you mean exactly and in which ways can we optimise imagery when design needs to be responsive?

**Comment by kenwheeler** [comment]
So a lot of CDN/Image hosts will let you request a certain size of image. On load, you can use this to request small images for mobile via a URL like img.png?w=330&h=180

**Comment by kenwheeler** [comment]
And while design needs to be responsive, 99% of people aren't resizing the window, so optimizing imagery for mobile users is worth making the images blurry for a QA dept or picky client that is playing scratch dj with the window size handle

**Comment by Rendez** [comment]
Haha, sure thing. I do play a lot of scratch DJ to break things.
