### ISSUE TITLE
wrapArrows option

### ISSUE THREAD

**Issue by Jako** [kenwheeler/slick#1798]
Hi Ken, would you accept a PR with a new option that wraps the navigation arrows around an element (Selector, jQuery object)? I have the following reason for this addition: third post on https://github.com/kenwheeler/slick/pull/1771

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because it [doesn't have a fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). You can submit a PR for review if you'd like, but I think you can accomplish what you're trying to do with current functionality with flexbox as long as you don't have to support older browsers. [Here's a codepen](
http://codepen.io/leggomuhgreggo/pen/VeyWoZ?editors=010) I whipped up. Hope that's helpful.
