### ISSUE TITLE
Horizontal scroll skips slides on Android devices when nav arrow is clicked

### ISSUE THREAD

**Issue by MoxxyTech** [kenwheeler/slick#1816]
Ref: http://jmarchinifarms.com/products/

When I advance the slider for the first time using the navigation arrows, the slider skips several slide positions. With the second click, the navigation scrolling works as expected. This response can only be duplicated on Android devices. iOS and desktop (Win/Mac) function as expected.

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), and it's kind of a support request but if you still feel like it's an actual bug you can whip it up in a fiddle. [Here's a boilerplate](http://jsfiddle.net/simeydotme/fmo50w7n/) for you to fork. For implementation help stackoverflow might be a safer bet. Thanks @MoxxyTech
