### ISSUE TITLE
Keyboard arrows don't work until click on slideshow (element focus)...

### ISSUE THREAD

**Issue by fabiocaccamo** [kenwheeler/slick#1817]
...I tried to call `$('.slick-slide').focus();` on dom ready to enforce slide focus, but in this way the other slides are now empty.

**Comment by elamprator** [comment]
What do you mean by other slides are empty?
-----------------------
Your Focus Call Works Fine Here http://codepen.io/EngCode/full/KdygXq/

**Comment by fabiocaccamo** [comment]
With 'empty' I mean other slides are just a white empty container without the image.
I don't use alpha transition but a slide from right to left transition.

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required) from OP, and it's kind of a support request but if you still feel like it's an actual bug you can whip it up in a fiddle. [Here's a boilerplate](http://jsfiddle.net/simeydotme/fmo50w7n/) for you to fork. Thanks @fabiocaccamo. @elamprator thanks a bunch for your help!
