### ISSUE TITLE
After dragging, 'slidesToScroll' should be ignored and should snap to the nearest slide

### ISSUE THREAD

**Issue by Sly-Ripper** [kenwheeler/slick#188]
Like the title says, it's an odd behaviour where you drag along 5 or so slides and it snaps back to the 2nd because 'slidesToScroll' = 1.

**Comment by surjithctly** [comment]
Hello,

SwipetoSlide does not work in reverse direction. even in Infinite mode. See gif below.

![slick](https://cloud.githubusercontent.com/assets/1884712/9288109/ec9dc438-4353-11e5-9d87-436b5f976236.gif)

**Comment by harrynewsome** [comment]
I'm experiencing the same issue @surjithctly mentioned above, is there a solution to this? 

// @kenwheeler

**Comment by potasiyam** [comment]
Hello guys, is there any progress on this issue?

**Comment by Tebzamops** [comment]
I am also experiencing the  same issue. I would really like to see this resolved.

**Comment by nominalaeon** [comment]
I'm experiencing this issue but with verticalMode. I tried figuring out how/where the code is firing the wrong position info, but it looks like it's doing it correctly.

...up until the dragging ends, and that's when the _.slideHandler fires _.setPosition() and it looks like it's using slideToScroll maths instead of the position that was calculated from the drag.

Here's the console log trail I put in:

<img width="704" alt="screen shot 2017-03-17 at 1 31 06 pm" src="https://cloud.githubusercontent.com/assets/1110469/24057686/2dd2bdd8-0b16-11e7-9b31-470eab0d03a3.png">

**Comment by zther-dev** [comment]
I'm experiencing the same issue @surjithctly mentioned above, can't go in reverse more than once for swipeToSlide

**Comment by akashnigam010** [comment]
For whoever is visiting, the issue reported by @surjithctly is resolved in version 1.6.0
Now reverse scrolling too works same as forward scrolling.

**Comment by veremey** [comment]
So, SwipetoSlide is fixed?
And heve I swipe slider more then 1 step, like a **surjithctly** show at  **commented on 15 Aug 2015** ?
Can show a code?

**Comment by MichalKliment** [comment]
Simple it was written in the documentation http://kenwheeler.github.io/slick/

in constructor option add parameter

{
...
**swipeToSlide: true,**
..
}

**Comment by RobertCody** [comment]
https://codepen.io/BMI/pen/ZRYeOB

**Comment by vicocotea** [comment]
I think it's an UX best practice and should be `true` by default, or be explained/mentioned with the slidesToScroll property.
