### ISSUE TITLE
Will Fade Effect not work for multiple items

### ISSUE THREAD

**Issue by shivansp** [kenwheeler/slick#1896]
Hello,
Can anyone tell me why fade affect is not working for this code,
wen i try the fade:true; its showing only one item and wen i remove fade:true; its showing two items.
i want items to fade and display at a time but its changing to one item wen i include fade:true;
can anyone help me with this

http://jsfiddle.net/mt4jdy6o/5/

**Comment by shivansp** [comment]
Hello,
@kenwheeler  can u please look into this and help me with this

**Comment by camrinp** [comment]
I'm having the same problem as well. Isn't this supposed to fade out the last item and fade the new one in?

**Comment by leggomuhgreggo** [comment]
Hey @shivansp I'm going to close this because this has the feel of a support request, but, I did some poking around and it looks at this point the fade effect is only supported for a single slide--there's a [feature request here](https://github.com/kenwheeler/slick/issues/830), and a [related issue here](https://github.com/kenwheeler/slick/issues/279). If you're feeling ambitions you're welcome to submit a PR. Thanks!
