### ISSUE TITLE
Slider jumping back to the beginning on infinite scroll

### ISSUE THREAD

**Issue by tonemichael** [kenwheeler/slick#1914]
The slider is almost working great but for some reason when trying to use infinite, once it reaches the last slide then attempts the loop, it pauses for a second then visibly scrolls right back to the first slide?

This ever been reported before?

Thanks

$('.variable-width').slick({
  dots: true,
  centerPadding: '0px',
  speed: 700,
  slidesToShow: 1,
  centerMode: true,
  variableWidth: true,
  infinite: true
});

**Comment by kenwheeler** [comment]
Closing due to not following CONTRIBUTING.md

**Comment by akeith2002** [comment]
I had this same issue and traced it back to my CSS applying a transition to body * which was overriding the .slick-track and .slick-list. I changed my call to `body *:not(.slick-track):not(.slick-list){}`

Hope that helps someone.

**Comment by SonnyCrockett** [comment]
adding to what @akeith2002 said, this issue cropped up for me because i had overriding styles on the `.slick-track` element in my stylesheet.

specifically it was the `transition` property i had placed on that element. once i got rid of it, Slick Slider stopped kicking back to the beginning when reaching the end of the set, and started looping as expected in an endless carousel of fun.

in order to make up for losing that `transition` in CSS, i added in some properties to the slider js, like so:

**REMOVED from CSS**
`transition: left 0.5s cubic-bezier(0.770, 0.000, 0.175, 1.000);`

**ADDED to JS**
```
speed: 500,
useTransform: true,
cssEase: 'cubic-bezier(0.770, 0.000, 0.175, 1.000)',
```

**Comment by sumanengbd** [comment]
Thanks, @akeith2002 I was scratching my head for the whole day to fix it.

**Comment by BB-000** [comment]
Hmm I also have this issue but definitely no overriding styles, check out this codepen (click from last slide to first slide dots), what's going on, it's not meant to be like this is it..?
https://codepen.io/bananafarma00/pen/PoYOmbP

**Comment by AntonGrekov** [comment]
have same problem , removed all transitions ... no help. gets even worse
