### ISSUE TITLE
variableWidth dot problem with slidesToScroll and centerMode false

### ISSUE THREAD

**Issue by raquelarnold** [kenwheeler/slick#1921]
Hallo,
I tried to find if these problems already were reported, but i didnt found/didnt look so deep

$('.variable-width').slick({
        dots: true,
        infinite: true,
        speed: 300,
        slidesToShow: 1,
        slidesToScroll: 3,
        centerMode:false,
        variableWidth: true
    });

1 Problem:
If you are in the first item and click in the back button: you will see half slider, it doesn't fill the items rightly into slider.

2 Problem:
With these configuration (slidesToScroll: 3) the amount of dots is wrong.

It is a very nice plugin. ;)
Regards

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). If you still feel like it's an actual bug feel free to whip up a fiddle. [Here's a boilerplate](http://jsfiddle.net/simeydotme/fmo50w7n/) for you to fork. Thanks!
