### ISSUE TITLE
Responsive Settings via Data-Tag

### ISSUE THREAD

**Issue by Skinwalker** [kenwheeler/slick#1951]
Is there a way to set the responsive settings via Data-Tag?

I tried:
```
<div class="slider" data-slick='{"arrows": false, "fade": true, "responsive": "[breakpoint: 992, settings: {fade: false}]}'>
```
but thats not working.

Anyone got an idea?

**Comment by tomaszpoliszuk** [comment]
{"arrows": false,"fade": true,"responsive":[{"breakpoint": 992,"settings":{"fade": false}}]}

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), and it seems like it might be able to be resolved with the suggestion from @tomaszpoliszuk. If you still feel like it's an actual bug you can whip it up in a fiddle. [Here's a boilerplate](http://jsfiddle.net/simeydotme/fmo50w7n/) for you to fork. For implementation help stackoverflow is a safer bet.

**Comment by halitguvenilir** [comment]
Thank you for the information.
