### ISSUE TITLE
SlickToGo not working on cloned slide

### ISSUE THREAD

**Issue by ldecoker** [kenwheeler/slick#1952]
Hello!

I have a slider defined as follows:

```
slider1.slick({
				arrows: true,
				dots: false,
				centerMode: true,
				slidesToShow: 2,
				slidesToScroll: 1,
				variableWidth: true,
				asNavFor: '#slider2,
});
```
This displays a list of several slides and one is centered. A click event has been added on each slide which use the 'slickGoTo':

```
$('#slider1 img').click(function() {
				var pos = $(this).parent().attr('data-slick-index');
				slider1.slick('slickGoTo',[pos, true]);
			});
```

The issue we have is that when clicking on elements located at the left (cloned element) on the center element (just after initialization), nothing happen (means no slide). With console.log, I verified that the click was attached to all elements (cloned and non-cloned).

Any idea on the cause?

Thx in advance.

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), and it's kind of a support request but if you still feel like it's an actual bug you can whip it up in a fiddle. [Here's a boilerplate](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required) for you to fork. For implementation help stack overflow is a safer bet. Thanks @ldecoker
