### ISSUE TITLE
initADA js error strange

### ISSUE THREAD

**Issue by skobeo** [kenwheeler/slick#1955]
Hi,
config: v 1.5.9
with multiple sliders + carousels on the same page, i had a strange issue with sometimes error message $slides is null (on initADA function)
So i had if(_.$slideTrack) {...}, and next in activateADA function if(_.$slideTrack) {...} and all is ok now

thanks

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because [there's no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), but if you whip one up we can check it out further. [Here's a boilerplate](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required) for you to fork. Thanks @skobeo
