### ISSUE TITLE
Prefer data-slick to general settings

### ISSUE THREAD

**Issue by SventB** [kenwheeler/slick#2011]
When using the attribute "data-slick"...
```
<div class="slick" data-slick='{"dots":false,"arrows":true}'>
```
together with a set of general options...
```
$('.slick').slick({
	dots: true,
	infinite: true
});
```
the default options are preferred: In the example above, the slider has dots although the setting in the data-attribute says "no dots".

For me, it seems more logical if the settings in "data-slick" overwrites the general options. For usage in a CMS this is highly recommended.

**Comment by leggomuhgreggo** [comment]
Interesting. I can see the logic there. Follows the same hierarchical pattern of inline CSS vs linked.

**Comment by kenwheeler** [comment]
Let's get this flagged as a bug and assigned.

**Comment by SventB** [comment]
Ok, this was an easy one ;)
Thank you for your fast reaction.

**Comment by simeydotme** [comment]
woah shit.... :cold_sweat:  

@kenwheeler I know we've not exactly been strict with the **semver** bizniz , but this could have a huge impact... I personally think this should be backed out and put in 2.0.0.

**Comment by kenwheeler** [comment]
I haven't cut a release for this yet, but this round of fixes will likely be 2.0. The real 2.0 landing at 3.0 or 4

**Comment by Dan503** [comment]
This is the completely wrong approach in my mind.

The JS will typically be called on a generic `.carousel` class.

The data attribute is called on the individual carousels. This gives much finer control of the settings to the data attribute.

If there are arguments for both sides then can we have a setting that determines what batch of settings have priority?

By default, the settings should merge rather than outright replacing one another.

**Comment by lincolnlemos** [comment]
I agreed with @Dan503 
Will be great if we can pass an arg in JS to set what is the priority.

**Comment by Dan503** [comment]
I re-read the issue. I guess I was somehow confused. I thought the issue was advocating for the default settings to override the data attribute settings when I wrote that comment. 😖

@lincolnlemos if you want to have the js settings take priority, maybe just remove the `data-slick` attribute from the element before initialization.

**Comment by vikaspaturi** [comment]
Hi Team,

How do we pass this as the Data attribute, I am looking for customPaging for below.

$(".cmp-carousel-single").slick({
    slidesToShow: 1,
    dots: true,
    infinite: false,
    arrows: true,
    **customPaging: function (slider, i) {
            return (
        '<img src="' +
        $(slider.$slides[i])
          .find(".cmp-carousel__content-wrapper")
          .attr("data-dot-title") +
        '">'
      );
    },**
  });
