### ISSUE TITLE
Can arrows be set to be permanently visible?

### ISSUE THREAD

**Issue by rickcurran** [kenwheeler/slick#2045]
I have sliders which sometimes have less than the required slides to make the arrows show, but I'd like to have the arrows be visible but disabled rather than removed. Is this possible?

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because there's [no fiddle](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required), and it's a support request, but my guess is you can do what you're trying to accomplish with the prevArrow/nextArrow options which allow you to define your own dom elements for the arrows.
