### ISSUE TITLE
slidesToScroll always 1 when using custom prevArrow and nextArrow

### ISSUE THREAD

**Issue by cannect** [kenwheeler/slick#2058]
Hi,

Exactly as my title says, I have a slide which has this setup:

```
$carousel.slick({
        asNavFor: '#slider .slick-slider',
        slidesToShow: 5,
        slidesToScroll: 5,
        centerMode: true,
        focusOnSelect: true,
        prevArrow: '#carousel .prev-arrow',
        nextArrow: '#carousel .next-arrow'
    });

$slider.slick({
        asNavFor: '#carousel .slick-carousel',
        slidesToShow: 1,
        slidesToScroll: 5,
        prevArrow: '#slider .prev-arrow',
        nextArrow: '#slider .next-arrow',
        speed: 200,
        swipeToSlide: true
    });

``` 

When disabling the prevArrow and nextArrow lines, the scrolling works for 5 items a time.

How to overcome this?

**Comment by leggomuhgreggo** [comment]
Hey, I'm closing this because it doesn't include a test case, [per the contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). Also it feels like it might be more of a support request than a bug report. If you make a fiddle, we can look at reopening. Thanks!
