### ISSUE TITLE
slickGoTo with RTL not working properly

### ISSUE THREAD

**Issue by NofarL** [kenwheeler/slick#2063]
When using ``rtl:true`` , the slickGoTo method goes to the wrong slide.

Removing ``rtl:true`` and wrapping the whole carousel with CSS ``direction:ltr`` works fine, so the problem is just with RTL.

Here is my code:

```javascript
$('.slick-horizontal').slick({
    cssEase: 'linear',
    rtl: true
});

$('.button').on('click', function(){
    $('.slick-horizontal').slick('slickGoTo', 3);
});
```

This doesn't go to the slide with the index 3. But if I remove the ``rtl:true`` it does work properly.

**Comment by simeydotme** [comment]
Could you please create a JSFiddle demonstrating your problem :)

**Comment by ifreaker** [comment]
I encountered the same issue and found it to be a problem with floats. 
Check slick.css line 85.
slickGoTo is working fine, the problem is the wrong slide being displayed in the browser. slick-active class is also on the right slide. It happens when html has dir="rtl"

I fixed this by overriding the CSS on my RTL slider with .slick-slider{float:left;}

**Comment by shamseerahammedm** [comment]
Option top change slider direction is not working as @NofarL  specified...

**Comment by layik** [comment]
@shamseerahammedm care to elaborate a little more? Not sure what you mean. Thanks

**Comment by shamseerahammedm** [comment]
@layik, I almost forgot about the issue, but I think I was talking about the direction of slides ( left to right or right to left ). Setting that option via js is not working for me, but it's working via CSS

**Comment by neticon-vandanahk** [comment]
Any solution ?
