### ISSUE TITLE
CSS not working 

### ISSUE THREAD

**Issue by amitdesai03** [kenwheeler/slick#2072]
This issue is exactly similar to #1270

Wierd characters for arrows.

I tried all suggestions on #1270 ....nothing worked...

**Comment by leggomuhgreggo** [comment]
If you're pulling files (fonts) from an external domain you probably need to configure access control headers on your server. It's hard to say, not knowing your exact environment, but [here's an article](https://davidwalsh.name/cdn-fonts) talking about it a little. 

I'm going to close this because it's not a bug with the library, and [doesn't conform to the contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required). Good luck!

**Comment by amitdesai03** [comment]
Just if someone stumbles into this issue,this would help.

Problem is the server side encoding which in my case was ISo-8859-1.

So either change server side encoding to UTF-8 to support arrow and dot characters.
OR
Define your own arrow class in the encoding your server supports.

**Comment by leggomuhgreggo** [comment]
Thanks for reporting back!
