### ISSUE TITLE
can't get AsNavFor working

### ISSUE THREAD

**Issue by JML89** [kenwheeler/slick#2073]
Hi,

I'm trying to use the feature asNavFor but in a slightly stylistic different way - see here:

http://wakes.mcm-zeus.co.uk/about/meet-the-team

Basically I want to show 3 images at the top and their related text. What happens is when they scroll through, they do not scroll the images. I have tried it so that they use one image and still no luck. I have tried a lot of the settings

The JS I use at the moment is:

$('.slider .img').slick({
        fade: false,
        slide: 'figure',
        slidesToShow: 3,
        slidesToScroll: 3,
        autoplay: true,
        pauseOnHover: true,
        asNavFor: '.slider .nav'
    });

    $('.slider .nav').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        asNavFor: '.slider .main',
        autoplay: true,
        pauseOnHover: true,
        dots: true,
        arrows: true,
        infinite: true,
        centerMode: true,
        focusOnSelect: true,
    });

Would be greatful if anyone could help me with this as soon as possible.

Cheers

**Comment by simeydotme** [comment]
JML since it's your first ever contribution to GIthub, and you signed up specifically for this... I will give you the benefit of hte doubt that you probably don't know what's happening here :smile: 

Actually, this is a place for reporting bugs or errors with code... so like... if you read hte documentation for Slick very thoroughly, and then the thing you were trying to do just doesnt work as you would expect (or at all) because it is behaving differently to the documentation... then you've possibly found a bug in Slick and we'd love to hear about it.

When producing bug-reports, it is generally accepted that you provide a "reduced test case" (https://css-tricks.com/reduced-test-cases/) to demonstrate the bug happening in a closed-environment where your own (perhaps buggy?) code is not interfering with the results. -- the best way is to use the provided (yup, we've already done hte hard work for you!) JSFiddle which can be found in the [contributing guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) (which, of course should have been read before posting a bug-report in GitHub).

The contribution guidelines are also a SUPERB place to start if you require support and help with your own coding problems (we all do sometimes) with links to forums and such to provide support if and when you realise that you actually have a difficult coding problem, and not, in fact , a bug.

Please don't get put off with open source. We're here to help... however there's places and times to get different types of help. And here on GitHub we're trying to make Slick a great plugin by fixing bugs. Stackoverflow is the place to get coding help and tips. :smile: 

Best of luck, Si.

**Comment by JML89** [comment]
Hi Si,

Thanks - I was actually reporting what I thought to be a bug. I just wanted to make sure with my code that I wasn't doing something stupid. I will make a reduced test case like you say (I have done this internally) and showcase it online for people to either help or recognise as a bug. I have read the documentation lots of times as I'm a big fan of the slider! Just on this case it doesn't want to behave how I'd like.

Cheers

**Comment by simeydotme** [comment]
No problem, and you can post your stsckoverflow question here, this time, for visibility of you end up creating one :) or head on to Gitter
