### ISSUE TITLE
Scroll on Hover

### ISSUE THREAD

**Issue by tone4407** [kenwheeler/slick#2093]
Is it possible to enable a scroll on hover? Something similar to what they're doing here:

http://www.mountaindew.com/

**Comment by leggomuhgreggo** [comment]
Hmm, I don't think you'd need--or really want--to use a proper slider in this case. It's similar in that you have a view port and array of elements sliding within, but I can't see how the slick functionality would be much use to something that hinges on mouse position, without any discrete slides to be transitioned to.

I'm going to close this, per the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required) because it's a support request, instead of a bug, but it was interesting. Thanks!
