### ISSUE TITLE
Empty space when slider reaches the last slide

### ISSUE THREAD

**Issue by wujekbogdan** [kenwheeler/slick#2099]
I have a slider containing variable width items. I set `variableWidth` to `true` and `infinite` to `true`.
When the slider reaches the last element then a gap after the last element shows up. When I scroll one more slide right then the gap i filled with the first element and the slider contiunes to loop. 

IMO it would be better if some of  first slides were cloned and appended to the end of the carousel in the initialization prosess not when the slider reaches the end. It would solve the issues like this.

**Comment by leggomuhgreggo** [comment]
Hey @wujekbogdan I'm going to close this because there's no fiddle; issues need to have a reduced test case for debugging purposed. [Check out the contribution guidelines.](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required)

It sounds like the issue your describing is a known one. [Here are some existing issues](projects-wrap) that might help clarify things for you. Thanks!

**Comment by ShabanSys** [comment]
There is empty space shown on first time load and then when we reach to last slide it shows me the empty space again and show the first slide with a jerk.
Is there any similar issue reported? If any please provide me the link to the issue. I am tired to getting this fix.
