### ISSUE TITLE
Remove slide by id

### ISSUE THREAD

**Issue by kevin20161** [kenwheeler/slick#2109]
Hi,

I tried to use this code from other thread to remove slides by id,

slickRemove($('#slider .slick-slide').indexOf('#yourID'))

I guess I should use like this,
$('.carousel').slick('slickRemove',$('.carousel').indexOf(id));

Javascrpt errors say "indexOf is not a function".

Thanks.

**Comment by leggomuhgreggo** [comment]
Hey @kevin20161 Im going to close this because it's a support request instead of a bug. Also there's no fiddle. Check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown).

That said, my guess is that since indexOf is a vanilla JS method, and not a jquery one, its not working on the jquery selection array. Like I say this is just a guess, but this might work:

`$('.carousel').slick('slickRemove',$('.carousel')[0].indexOf(id));`

**Comment by samjonesigd** [comment]
@leggomuhgreggo doesn't work for me, I get `indexOf is not a function error`

**Comment by samjonesigd** [comment]
also trying to remove by class name not ID

**Comment by leggomuhgreggo** [comment]
Can you put it in a codepen/fiddle?
