### ISSUE TITLE
Nested slider issue

### ISSUE THREAD

**Issue by jma689** [kenwheeler/slick#2117]
I have slider A and slider B that are synchronized. Inside each slide of slider B, I have a centered Slider C. Whenever I click on slider A to change the slide in slider B, it also delete any .slick-current or .slick-center classes from my slide in slider C. 
How do I keep the .slick-current class in my first slide of slider C?

```
<div` class="A">
		<div>JAN</div>
		<div>FEB</div>
		<div>MAR</div>
		<div>APR</div>
	</div>
	
<div class="B">
	<div class="C">
		<div>Sun 01 3PM</div>
		<div>Mon 02 7pm</div>
		<div>Tue 03 3PM</div>
		<div>Tue 03 7PM</div>
		<div>Wed 04 3PM</div>
		<div>Thu 05 7pm</div>
		<div>Fri 06 3PM</div>
		<div>Sat 07 7PM</div>
		</div>
		
	<div class="C">
		<div>Sun 01 4PM</div>
		<div>Mon 02 7pm</div>
		<div>Tue 03 3PM</div>
		<div>Tue 03 7PM</div>
		<div>Wed 04 3PM</div>
		<div>Thu 05 7pm</div>
		<div>Fri 06 3PM</div>
		<div>Sat 07 7PM</div>
	</div>
		
	<div class="C">
		<div>Sun 01 5PM</div>
		<div>Mon 02 7pm</div>
		<div>Tue 03 3PM</div>
		<div>Tue 03 7PM</div>
		<div>Wed 04 3PM</div>
		<div>Thu 05 7pm</div>
		<div>Fri 06 3PM</div>
		<div>Sat 07 7PM</div>
	</div>
		
</div>
```

**Comment by leggomuhgreggo** [comment]
Hey I'm closing this because there's no test case (check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown)), but I can tell you that it's a [known issue](https://github.com/kenwheeler/slick/search?q=nested&type=Issues&utf8=%E2%9C%93) and will likely be sorted for the next release.

Thanks!

**Comment by ArthurShlain** [comment]
Solution (tested with v1.6.0):
https://jsfiddle.net/ArtZ91/ev4aL0gu/
