### ISSUE TITLE
Slides to scroll and slides to show preview

### ISSUE THREAD

**Issue by seesoe** [kenwheeler/slick#2126]
I'm using 4 as my slides to scroll and 5 as slides to show. Is there a setting or a way to make only half of the 5th slide show? So as if it's a preview of what a user can slide to?

**Comment by leggomuhgreggo** [comment]
Hey I'm going to close this because it doesn't conform to the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown), but I think people have tried to enter decimals for those values. There's also centerMode which kind of does that with the proper padding. Good luck!

**Comment by seesoe** [comment]
Entering a decimal for slide display is exactly what i needed thanks! (should've tried the obvious)
