### ISSUE TITLE
Flicker while page is loading

### ISSUE THREAD

**Issue by johanngonzalez** [kenwheeler/slick#2143]
I've set up a minimal example using a simple HTML + Bootstrap + Slick JS carousel.

The problem is that every time the page starts loading, slick js carousel makes and annoying flicker/blinking.

I've set up an example here:

http://rewind9.com/flicker/examples/starter-template/index.html

I've verified and the order scripts are being loaded is correct. Here is how I call the carousel.

<script type="text/javascript">
  $(document).ready(function(){
    $('.carousel').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 2000,
    });
  });
</script>

I thought this was a CSS issue so I even tried hiding the overflow on the main div, without success.

.carousel {
  position: relative;
  overflow: hidden;
  background-color: red;
}

Any ideas what else I could try?

Using: bootstrap-3.3.6 and slick 1.5.9

**Comment by leggomuhgreggo** [comment]
Hey! if you search previous issues you'll find a bunch of different methods you can use to accomplish this, most of them hinge around the addition of the `slick-initialized` class. Here's one: #779 

Alternatively you could always style your slides so that they're inline, no-wrap, instead of being block.

Since there's no standardized class for pre slicked elements, it's not something that can really be baked into the slick styles.

Hope that helps!
