### ISSUE TITLE
Slick using 'left' instead of 'transform3d'

### ISSUE THREAD

**Issue by adrianparr** [kenwheeler/slick#2174]
> My carousel is not using translate3d like it should do. It is falling back to using 'left' offset instead.

====================================================================

#### CodePen demo

[http://codepen.io/adrianparr/pen/wKQxjb](http://codepen.io/adrianparr/pen/wKQxjb)
I already had a CodePen which highlighted the problem.

====================================================================

#### Steps to reproduce the problem

Inspect the '.slick-track' element using the Developer Console. You can see that the scrolling is done using 'left' rather than CSS3 'transform' even though you're using a modern browser.

====================================================================

#### What is the expected behaviour?

I'd expect it to use CSS3 transforms when it is available. 

====================================================================

#### What is observed behaviour?

Slick is using 'left' positioning instead.

====================================================================

#### More Details

- Which browsers/versions does it happen on?
Chrome 48
Firefox 44
Not tested on IE

- Which jQuery/Slick version are you using? 
Slick 1.5.9

- Did this work before?
I had it working last week. It has only stopped working recently.

**Comment by leggomuhgreggo** [comment]
Because the library supports older browsers, like ie8, it doesn't use the transform prop. Without additional user agent JS like modernizr I can't think of a good way to make a programmatic distinction for the older browsers, but if you have an idea I'd be interested.

In case you're noticing a lag, there was [this bug](https://github.com/kenwheeler/slick/issues/2078), which you can fix with `useTransforms: true`. Im going to close this because it's not quite a bug, but can reopening if you have somethin up your sleeve. Hope that helps! Thanks!

**Comment by adrianparr** [comment]
Thanks @leggomuhgreggo , that solved my issue.
By the way, it looks like the parameter is ...

useTransform: true

(singular, not plural)

**Comment by alvarotrigo** [comment]
> Because the library supports older browsers, like ie8, it doesn't use the transform prop. Without additional user agent JS like modernizr I can't think of a good way to make a programmatic distinction for the older browsers, but if you have an idea I'd be interested.

What about [this solution](http://stackoverflow.com/a/12621264/1081396).

Used in [my own library](http://alvarotrigo.com/fullPage/).

**Comment by leggomuhgreggo** [comment]
Hey @alvarotrigo I was a little off the mark with that comment. It's true that the library supports ie8 but because the performance is so crucial, the positioning *is* actually done by transform by default.

The matter is complicated by the fact that last release (1.5.9) the default was accidentally set to `useTransform: false` so you have to specify the setting to get it to work, but it's fixed in the master.

Anyway, I hadn't connected the dots on it when I wrote that. Sorry for the confusion!

**Comment by alvarotrigo** [comment]
No problem thanks for it!! 
Working good now!
