### ISSUE TITLE
Prevent preload of _any_ image?

### ISSUE THREAD

**Issue by deefens** [kenwheeler/slick#2175]
Is there any option to prevent _every_ preload? I've learned so far, that the first image of a slide gallery is preloaded in every case, which is a no go for my use case (mobile web application with an image slider as full view navigation).

At the moment I'm tricking a bit, as I add an empty slide to prevent the preload, but this is not an elegant solution.

**Comment by leggomuhgreggo** [comment]
Hey @deefens There's an option for lazyLoad which sounds like what you're looking for. Im going to close this because it's not really a bug. Also check out the [contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown) for more details on issues/bugs etc. Thanks!

**Comment by stratboy** [comment]
How about the ability of disabling lazyload?
