### ISSUE TITLE
Issue Sliding from first to last and last to first as slick-active and slick-current classes are added after a delay

### ISSUE THREAD

**Issue by rana3012** [kenwheeler/slick#2183]
> `slick-current` and `slick-active` classes not added properly on navigating from first to last or last to first
====================================================================

Please find the below fiddle for more details. My use case is depicted in it which has an svg image. Although the issue can be seen without any image/svg in it. 

Also the `slick-current` doesn't seem to get added if we navigate to another state and press browser back button (When included in angular app, no fiddle is provided for this scenario)

###### `https://jsfiddle.net/rana3012/fgdow4tw/2/`  

use this jsfiddle to reproduce the bug: 
https://jsfiddle.net/rana3012/fgdow4tw/2/

====================================================================

#### Steps to reproduce the problem

1.Navigate to last slide / first
2.If last, navigate next and if first, navigate to previous. 

====================================================================

#### What is the expected behaviour?

The slide should move to next as if there is no stop.

====================================================================

#### What is observed behaviour?

There seems to be a lag/flickering. 

====================================================================

Should I be looking for something else instead of the `slick-active` and  `slick-current` classes to style appropriately?

**Comment by leggomuhgreggo** [comment]
This is a side effect of the cloning. The issue of course is that the `slick-current` and `slick-active` classes are applied for active slides, and the cloned slides become active before those classes are applied.  

I can see an argument for applying the slick current class to the clone, but I have doubts as to whether that would really get the job done, because sibling selection would be so insane. Moreover, slick-current being exclusive to an active slide is something I can understand people leaning on.

Cloned slides copy the base markup for a slide, so if you use an attribute to identify a slide in the original markup, you can target that and add classes based on the position to both the original and the cloned slides. 

[Here's an example I rigged up](http://codepen.io/leggomuhgreggo/pen/vGLzgP?editors=0111), just extending with events. It's ugly and I think there's probably some inefficiencies, but it doesn't jump. 

I don't see a great solution in terms of enhancing the library, but I'd love to hear some ideas. Until then Im going to close this. Thanks!
