### ISSUE TITLE
Bitdefender blocked this page

### ISSUE THREAD

**Issue by mhakes** [kenwheeler/slick#2189]
> short description of the bug / issue, provide more detail below.
FYI Demo link being blocked by Bitdefender antimalware feature. See image
====================================================================
![image](https://cloud.githubusercontent.com/assets/1183920/13606354/46e01ec8-e511-11e5-938b-4198e77c1b1f.png)

###### `[  paste your jsfiddle link here  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Hey @mhakes. Thanks for the heads up. This is the second issue I've seen about bitdefender hitting the demo site with a false positive. I went ahead and filed a "false positive" report with them here:

http://www.bitdefender.com/submit/

Feel free to do the same. 

I looked at it a week or so ago, and the only reason I can think for why it'd be getting hit is because some CDN resources have cookies and maybe it doesn't like that. Hopefully it get's cleared up soon.

**Comment by leggomuhgreggo** [comment]
Here's the auto-response from bitdefender:

>Thank you for the data provided. We have sent it to our laboratories for specialized analysis. If a false positive is found, detection will be removed in the next 72 business hours. Should you need further assistance in the future, please do not hesitate to contact us.

>Thank you,
>Bitdefender Customer Care Team

**Comment by mhakes** [comment]
I'll file the false positive with them as well. Keep up the good work.
