### ISSUE TITLE
Oversized images flicker

### ISSUE THREAD

**Issue by eladnova** [kenwheeler/slick#2203]
> short description of the bug / issue, provide more detail below.

Hi
I don't know if this is a clash with Foundation 5 / 6 but when I use Slick with Foundation there is a loading issue. The screen will display oversized images which are stacked vertically.
Once the script loads, the images resize to their proper widths and heights in the slider.

**Comment by leggomuhgreggo** [comment]
Hey! if you search previous issues you'll find a bunch of different methods you can use to accomplish this, most of them hinge around the addition of the `slick-initialized` class. Here's one: #779 

Alternatively you could always style your slides so that they're inline, no-wrap, instead of being block.

Since there's no standardized selector for pre slicked elements, it's not something that can really be baked into the slick styles.

Hope that helps!

**Comment by eladnova** [comment]
Thanks guys. Found a few related posts.
