### ISSUE TITLE
Slick-arrows aren't removed from DOM  when settings : "unslick" is used

### ISSUE THREAD

**Issue by k-lusine** [kenwheeler/slick#2208]
>  Slick arrows aren't removed from DOM when I set settings : "unslick" in breakpoint

====================================================================

###### `[  http://jsfiddle.net/fmo50w7n/279/  ]`  

====================================================================

#### Steps to reproduce the problem

1. Resize the window until slider is inslicked
2. Resize back (I use $(".slider).slick("reinit") to reinit the slider as it doesn't respond to internal resize as slick is removed. I have found that solution in one of the issues)  and you can see more than two arrows.
3. Most of them are one on another, but if you look html, you can see them

P.S. If you could suggest another solution to reinit slider, after slick is destroyed, that would be great

====================================================================

#### What is the expected behaviour?

The arrows should be removed from DOM

===================================================================

#### What is observed behaviour?

The arrows are  not removed and if you resize several times you can see list of slick-arrows  one on top of another, 

====================================================================

#### More Details

- Which browsers/versions does it happen on? It happens both on Firefox and Chrome
- Which jQuery/Slick version are you using?
I've used the fiddle you provide
- Did this work before?
I haven't tried

**Comment by leggomuhgreggo** [comment]
Hey @k-lusine legit issue. There're a couple others that have some good discussions on it, I think [this one](https://github.com/kenwheeler/slick/issues/542) might be the most robust. Definitely on the radar. Hope that's helpful. Thanks.

Closing: duplicate

**Comment by k-lusine** [comment]
Thanks for answering, I hate reopening this, but @leggomuhgreggo let's forget about reslicking for a moment. Don't you agree that settings: "unslick" should remove everything related to slick, including arrows, what I mean, we should have the same behavior as $(".slider").slick("unslick"). 

The reason why I don't use it, is the following. It isn't unslicked when I resize from a breakpoint,  but it's another issue :))

**Comment by leggomuhgreggo** [comment]
@k-lusine sorry for not addressing the main focus of your issue when I closed. The arrows do get removed when it unslicks.

There are extra arrows because `reinit` adds them. When you initialize an already initialized slider `buildArrows` gets run, adding as many sets of arrows as there are reinits. Since it's tied to the resize event, there's a lot!

Dug into it and there's another layer of complexity in that, when there's a breakpoint and the options get shifted, the arrows are appending within slick track, which is why you see arrows being added inside the slider area.

Looks like one of the fixes (at the bottom) from the issue I mentioned previously conditions the reinit to prevent this issue. 

I think it might make sense add a test to the `reinit` method. I think some people use it as a refresh, for things like responsiveness, so maybe just testing to see about the arrows? 

[Here's another discussion](https://github.com/kenwheeler/slick/issues/1380) with more up to date info on the subject of unslick/reslick. 

Hope that helps clarify. Thanks!

**Comment by k-lusine** [comment]
@leggomuhgreggo thanks again

**Comment by leggomuhgreggo** [comment]
Oh hey so I dont think `reinit` is technically a supported method. It's not in the docs, and used internally in conjunction with another undocumented method called `unload`. That would solve the duplicate arrow issue.

I think your main issue is how to deal with an reslick an unslicked slider at a breakpoint and [this](http://jsfiddle.net/fmo50w7n/342/) should do the trick, courtosey of @jon-mann. Hope that helps.
