### ISSUE TITLE
slick arrows disappear

### ISSUE THREAD

**Issue by wwwApp** [kenwheeler/slick#2227]
Hi,
I'm a beginner in JavaScript and I was using Slick plugin on my assignment
to give slide show to the list of items.
I got to the part where I can use li's of ul to create the slide show, but I wasn't able to
figure out how to get buttons work the way I want.

So, the first issue is that I don't see the default arrows at all.
I tried changing css, but it didn't work.
After that, I was trying to trigger the slide show manually using the buttons I created,
and it didn't seem to be working. To do this, I added 'prevArrow' in the setting.
But, as soon as added those settings, the buttons disappear.
(I also tried changing css)

====================================================================

$('.work-list-wrapper').slick({
	slide: 'li',
        dots: false,
        arrows: true,
	slideToShow: 4,
	slideToScroll: 1,
	prevArrow: $('.work-list-previous'),
	nextArrow: $('.work-list-next')
});

So the .work-list-wrapper is the div that contains the ul.work-list
and within that div, I have two a's (.work-list-previous and .work-list-next) as arrows.

For additional details:
- I have only four images and I want them to loop infinitely.
- ul.work-list looks like this: 
 
     <         image 1         image 2         image 3        image 4         >
     (a)        (ul.li)                (ul.li)              (ul.li)             (ul.li)         (a)

====================================================================

Thank you for the help!

**Comment by leggomuhgreggo** [comment]
Hey @wwwApp, hard to say without a fiddle ([see contribution guidelines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown#test-case-required)) but typically this happens because the arrows are positioned outside the slick-slider div and the overflow is hidden either because it is specifically set to be hidden or its full width and is outside the width of the window.

Hope that helps!

Closing: no test case, support req
