### ISSUE TITLE
swipeHandler should check whether target.tagName is input or textarea to allow drag inside input and text area

### ISSUE THREAD

**Issue by systembugtj** [kenwheeler/slick#2291]
if have input inside slide, and turn on draggable, will not be able to drag and select the test.

Simple workaround is that in swipeHandler add a check to avoid drag when inside input and textarea

Slick.prototype.swipeHandler = function(event) {
        if (event.target.tagName === "INPUT" || 
            event.target.tagName === "TEXTAREA") {
          return;
        }
.....

**Comment by systembugtj** [comment]
I would like to submit a PR, but not sure how to build it.

**Comment by leggomuhgreggo** [comment]
Hey @systembugtj I think the first thing to do is to make a test case of your issue here, in a fiddle or something. Might be something you can do short of a full fledged PR, but the test case is generally a pre-req for debugging efforts. 

If it ends up calling for the PR, you just fork the repo, make your modifications and create the PR with explanation and some demos to make sure its working.

I'm going to close this pending a test case. Thanks!
