### ISSUE TITLE
Lazyload - background images?

### ISSUE THREAD

**Issue by drawcard** [kenwheeler/slick#2312]
Hi, I was wondering if there was a method to make the lazyload feature work for images set as "background-image" in CSS on each slide? Thanks.

**Comment by llos** [comment]
I think you should custom code it. Here is an example of a custom lazyload applied on beforeChange event. In this case I'm loading the next two images. The second one a bit later than the first one. Hope this helps you implement the background lazyload feature ;-)

```
beforeChange: function (event, slick, current_slide_index, next_slide_index) {
	var img = $(event.currentTarget).find("[data-slick-index='"+next_slide_index+"'] img"),
	img2 = $(event.currentTarget).find("[data-slick-index='"+(next_slide_index+1)+"'] img");
	img.attr('src', img.data('llos-lazy'));
        setTimeout(function(){
		img2.attr('src', img2.data('llos-lazy'));
	}, 300);
}
```

**Comment by leggomuhgreggo** [comment]
Nice @llos!

**Comment by fahdi** [comment]
For someone who is trying this and it's confusing, the reason is as follows

**In slick 1.4, callback methods have been deprecated and replaced with events. Use them as shown below:**

`// On before slide change
$('.your-element').on('beforeChange', function(event, slick, currentSlide, nextSlide){
  console.log(nextSlide);
});`
