### ISSUE TITLE
Is there any way to change the thumbnail strip size?

### ISSUE THREAD

**Issue by absalone** [kenwheeler/slick#2389]
Hi there,

I'm wondering how to change the thumbnail strip size.
I would like to have them bigger than it is at the moment (taller, and less spacing in between). 
I would also like to make the thumbnail strip larger than the image shown on the carousel.
(here is my carousel http://cezanne01.businesscatalyst.com/photographs.html)
Do you have any suggestion how I could achieve that?

Thanks,
Matt

**Comment by ahmadalfy** [comment]
If you need to customize your thumbnail specifically to each slide you can use the `customPaging` property and attach a data attribute with the value of the exact content of the pagination thumbnail. In a previous project I wanted to use text on the buttons so I created a function like this:

```
  var textAsButton = function(slider, i) {
    return '<button type="button" data-role="none" role="button" aria-required="false" tabindex="0">' + $(slider.$slides[i]).data('title') + '</button>';
  };
```

Then I called it during initialization:

```
....
  customPaging : textAsButton
}
```

You can use something similar ... But instead of just adding text you can modify the function to create an image tag and attach the corresponding thumbnail as a data attribute.

Regards
