### ISSUE TITLE
Content security policy

### ISSUE THREAD

**Issue by ShadowDancer** [kenwheeler/slick#2399]
> Slick slider is not CSP compliant https://en.wikipedia.org/wiki/Content_Security_Policy
====================================================================

No fiddle because it requires server headers

====================================================================

#### Steps to reproduce the problem

1. Enable CSP on your server
2. Add slick

====================================================================

#### What is the expected behaviour?

Beautiful and safe website

====================================================================

#### What is observed behaviour?

CSP stopped execution because of this:
```
        _.$slides.each(function(index, element) {
            $(element)
                .attr('data-slick-index', index)
                .data('originalStyling', $(element).attr('style') || '');
        });
```

```
        if(_.options.rows > 1) {
            originalSlides = _.$slides.children().children();
            originalSlides.removeAttr('style');
            _.$slider.empty().append(originalSlides);
        }
```

```
        if (_.$slides) {

            _.$slides
                .removeClass('slick-slide slick-active slick-center slick-visible slick-current')
                .removeAttr('aria-hidden')
                .removeAttr('data-slick-index')
                .each(function(){
                    $(this).attr('style', $(this).data('originalStyling'));
                });
```
- setting inline style!

====================================================================

#### More Details

- Which browsers/versions does it happen on?
All browsers supporting CSP
- Which jQuery/Slick version are you using?
Present in slick/slick.js in master branch
- Did this work before?
Nope?

**Comment by kenwheeler** [comment]
Whats the fix here? Sanitizing the originalStyling data ?

**Comment by ShadowDancer** [comment]
I'm suprised that noone in web knows about https://en.wikipedia.org/wiki/Content_Security_Policy
It's here for few years already, and it completly solves XSS problems.

Fix is to stop using inline styles .attr('style', something).

**Comment by kenwheeler** [comment]
Yeah that's not gonna happen

**Comment by kenwheeler** [comment]
Ok so it looks like using the CSS object model to store and reapply those styles is the actual fix. If anyone cares to PR that, I'll gladly take it.

**Comment by ShadowDancer** [comment]
For what purpose you need inline styles?

**Comment by kenwheeler** [comment]
For literally everything having to do with dynamically positioning elements?

**Comment by kenwheeler** [comment]
After reading the spec, it's not about having inline styles it's about how they are applied. CSS object model is compliant"

**Comment by ShadowDancer** [comment]
Well depends on definition of inline :) I was using terminology from spec.

If you could provide some introduction for my frontend dude I think that he could contribute in near future (of course only if you want to be compilant ;)).

**Comment by kenwheeler** [comment]
If those are the only offending lines, it shouldn't be too hard to refactor into compliance. What's the best way to get a CSP error thrown, so I can reproduce this?

**Comment by ShadowDancer** [comment]
You need to add csp header on your server, for example:
`content-security-policy: default-src 'self'`
and then load document returned by that server. You will see error in console saying 
`Refused to apply inline style because it violates the following Content Security Policy directive (...)`.

I am not sure if that are only offending lines. I just checked for 
"attr('style', ...)" in source (afaik it directly modifies the DOM, and forces browser to reload styles from attribute thus rejecting style as inline).
Csp also forbids inline javascript (in `<script>` tags or in attributes, for instance `onclick="sayHi(event);"`). I don't see any eval, so that's good.

**Comment by leggomuhgreggo** [comment]
Did some ctrl + f for 'attr' in the source and looks like the only lines where the style attribute is targeted are [516](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L516) [816],(https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L816), and [884](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L884)

And if it's only the application of styles using the attr (and not retrieving/removing the value), then [884](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L884) is the only culprit.

After googling the subject a bit, I didn't find any way to directly take the properties in a style attribute value and apply them using the CSS Object Model, so I wrote wrote a function to parse it, [here](http://codepen.io/leggomuhgreggo/pen/VjbOmB?editors=0010).

@kenwheeler didn't want to PR it in case you'd already made headway on the issue/had set up a testing environment, but let me know if the above thinking makes sense to you and would like me to tackle it.

Thanks!

**Comment by ShadowDancer** [comment]
I think that you are fighting problem that does not exist ;)  If csp is on there won't be style attribute, so script should do nothing (not even attempt to set/clear style attribute). I think that just reading style attribute does not trigger csp violation.

**Comment by leggomuhgreggo** [comment]
Oh hmm, maybe I'm confused--I thought: a) the implementation of slick with the CSP enforced was throwing an exception; and b) that exception could be circumvented through the use of CSS Object Model, as opposed to the use of the `style` attribute.

**Comment by ShadowDancer** [comment]
Yes, that''s right. But most styles are applied using CSSOM already (css() jquery method). Slick uses style attribute only for managing original styles - originally present on that attribute (am I right?). The only problem arises when slick tries to clear style attribute (which is not there, because CSP in on).

**Comment by leggomuhgreggo** [comment]
Okay, ye, thanks for clarifying. 

So here's my understanding:

There are three lines in the js ([detailed here](https://github.com/kenwheeler/slick/issues/2399#issuecomment-231536543)), where the jQuery attr method is use in connection with styles. The reason they exist at all is so that if a slick needs to be unslicked, any inline styles that existed on the elements prior to a slick init, can be reapplied when the slick is destroyed so it looks as nature intended. 

The three lines correspond to: 1) retrieving the styles, and storing them in the slick object; 2) removing the existing styles, in preparation for the application of slick's inline styles (applied, as you say, using the CSSOM); and 3) reapplying the original styles back if the slick destroy method is called.

My guess at this point is that the offending lines were just the removal and reapplication of the styles, and not simply the retrieval/storage of them. Assuming that is the case, I'm thinking we'll need one function for the removal of the styles, where I guess we parse the styles in the attribute and set the value to initial, and then another function to reapply, which I believe is at least partially satisfied by what I wrote in the [codepen](http://codepen.io/leggomuhgreggo/pen/VjbOmB?editors=0010). 

If the retrieval and storage of initial styles using the attr method violated the CSP policy, then I'm not sure what, if it exists, is the compliant way to do that.

Sounds like you're going to get deep on this in the near term, which is awesome. Let me know if all that makes sense to you and your front-end colleague. 

Thanks!

**Comment by leggomuhgreggo** [comment]
@ShadowDancer how'd this go for y'all?

**Comment by leggomuhgreggo** [comment]
Closing: dormant
