### ISSUE TITLE
Add lazy load to background images

### ISSUE THREAD

**Issue by zslabs** [kenwheeler/slick#248]
Hi all,
Love Slick, thanks for creating this! Was wondering if the lazy load logic could also be added to background images that may be attached to each slide. Right now I'm using `background-size:cover` on desktop (and manually setting the height) compared to swapping the background out for a static image on smaller devices. I could obviously add the lazy load handler for the inline images, but they'd be loaded regardless because of the background image reference. Thanks!

**Comment by andrewtibbetts** [comment]
I often have slides generated from a database (images + etc are set in CMS) and are therefore not available to CSS. And having inline images act like background-size:cover takes some js trickery and is a real pain. This would be of great help to me.

**Comment by hultberg** [comment]
@andrewtibbetts @kenwheeler I have a PR waiting to do this. #916

**Comment by SomniusTiger** [comment]
I use `background: cover;` for a large number of background images that I work with, so this feature would be greatly helpful to me. When I do this, I set the background image through a `style` attribute on a div, so that way the image is still set in the markup. 

I do this specifically because I still want to set the image through the markup, but I want to be able to control how my background images are sized within their containers. Hopefully setting the image through the workflow I just described makes this more feasible!

**Comment by Abderezai** [comment]
I also use slick with background-image inline CSS. It fits to the div perfectly this way. But all images load at once. Would really appreciate progressive lazy loading to work in this case.

**Comment by Gouvi** [comment]
+1 to this feature.

**Comment by geo1004** [comment]
+1 would be a nice feature. No news for a while

**Comment by STPo** [comment]
+1 !

**Comment by Abderezai** [comment]
You can implement this yourself with javascript and jquery by updating the CSS of each slide to include the background image. You can do a look ahead to make sure the N + 3 slides have their background image's set.

**Comment by RobDong** [comment]
+1 to this feature.

**Comment by carmolim** [comment]
+1 to this feature.

**Comment by Sanabria** [comment]
+1 Please!

**Comment by simboonlong** [comment]
A DIY example I've came up with: 

[lazybgimg.html](https://gist.github.com/simboonlong/7e2d6fd86efd7398a9ac19e47caa80ef)

Hope it helps.

**Comment by oneextra** [comment]
I use the lazyLoaded Event and replace the src attribute with the background attribute. Looks something like this: 

```
$('.ref-slider').on('lazyLoaded', function (e, slick, image, imageSource) {
        
       image.attr('src',''); //remove source
        image.css('background-image','url("'+imageSource+'")'); //replace with background instead
        image.css('background-size','cover');
        image.css('background-position','center');
        image.css('background-repeat','no-repeat');

    });
```
Maybe this helps!

**Comment by MarieComet** [comment]
Hi @oneextra,
I'm trying to implement your snippet, but there is a problem because you are removing the image src attr : 
`image.attr('src',''); //remove source`
Before adding it to the background-image...
Also, if i modify your code like this : 

```
$('.slickslider-full-width').on('lazyLoaded', function (e, slick, image, imageSource) {
     imageSource = image.attr('src'); //remove source
     parentSlide = $(image).parent('.slick-slide.slick-current');
     parentSlide.css('background-image','url("'+imageSource+'")'); //replace with background instead
     image.attr('src','');
 });
```
I don't see any better lazyloading... What I am missing ?

**Comment by oneextra** [comment]
@MarieComet  I didn't try it the other way around, removing the src AFTER adding the background image. I don't know, but why should this make a difference, you can have both, the src attribute should be overriding it. The only thing that changes is the dimension of the image, since it is now "empty", without the soruce. So make sure that the img has a min-height/height and width set somehow, since without the image itself the slide might have a height of 0 and not be visible.  

Just to exclude the easiest explanation: Are you sure you haven't forgotten to activate lazyLoading on the slider or something? And are you sure you have correct image source provided? 

But the code you are seeing is precisely the code I am using at http://ihrehausnummer.de/ and it works fine for me.  (However the image will have a light gray outline of an empty image, that I cover up with an absolutely positioned container + 2 px white border.)

Also you don't need to retrieve the src of the image from the image itself, because it is passed to the lazyLoaded callback anyway. 

Like this you get the benefits of background-image with and the benefits of lazy loading. 

Good luck

**Comment by ashrafreda** [comment]
Thanks **oneextra**, work correctly.

**Comment by DennisLypovetsky** [comment]
Thanks @oneextra, works brilliantly! Except that I removed  `image.attr('src',''); //remove source`, because to use Slick's `lazyLoad: 'ondemand'` we have to replace src in `<img>` tag to data-lazy. 

Like this: 
`<img(data-lazy="img/main-bg-1.jpg"/>`

**Comment by sjclark** [comment]
+1 Amazed this has been talked about for years but never implemented

**Comment by PopcornDesign** [comment]
+1 Still waiting for this.
Perhaps lazy load for background images like blazy.js

<div class="slick-lazy" data-lazy="YOUR-IMAGE-URL"></div>

Read upon BlazyJS documentation, would be perfect if merged into slick

**Comment by tackenco** [comment]
Hi @oneextra, Just found your solution, perfect. Thanks!

For me, I usualy use a div with the background image attached and simplified your code like this:
`$('.ref-slider').on('lazyLoaded', function (e, slick, image, imageSource) {
        image.parent().css('background-image', 'url("' + imageSource + '")');
        image.hide();
 });`
My surrounding div has all the style set in the css and only the background image style is set inline. The image is just hidden and won't bother you no more ;-)

Thanks again!

**Comment by emrebostan** [comment]
$(".img-lazy").lazyload({data_attribute: "src",load: function() { $(this).removeClass("img-lazy") }});
$("#slider").mouseenter(function(){
		$(this).find(".img-lazy").each(function(){
			$(this).css("background-image","url(" + $(this).data("src") + ")").removeClass("img-lazy");
		});
});

**Comment by matias-autio** [comment]
Instead of setting the image source to empty, I replaced it with a transparent gif (copied from [`bLazy's demo page`](http://dinbror.dk/blog/blazy/?ref=demo-page) like this:
 

`image.attr('src','data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==');`

That removes the problem of missing source image having a light gray outline. (Thanks @oneextra for a great fix).

**Comment by mobiusint** [comment]
Not sure this helps anyone, but I was trying to figure out how to lazy load both mobile & desktop images and this seems to work with two data attributes. Not sure if something better was added prior to me commenting.

**Here is my image tag**
`<img data-desktop="desktop-image.jpg" data-mobile="mobile-image.jpg" data-lazy="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">`

**Here is the Lazy Loaded** 
`
$(".slider").on("lazyLoaded", function(e, slick, image, imageSource){

     var my_slide = image.parent();
     var desktop_image = image.data('desktop');
     var mobile_image = image.data('mobile');
     image.attr('src','data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==');

     //set the correct image based on size of screen
     imageSource = desktop_image;
     if(jQuery(window).width()<768){
       imageSource = mobile_image;
     }
     my_slide.css('background-image','url("'+imageSource+'")'); 
   });`

You can set the rest of your css background repeat, size, etc in your class name for the bg image.

Let me know if this works for anyone else or if you see any issue.
