### ISSUE TITLE
Slider Syncing : Pause on slider nav hover

### ISSUE THREAD

**Issue by meneldil** [kenwheeler/slick#2493]
Hello,
Is there an equivalent to `pauseOnDotsHover: true` when using the setting `asNavFor`?

Thanks in advance. ;)

**Comment by leggomuhgreggo** [comment]
Hey @meneldil can you make a reduced test case? There's a jsfiddle you can fork from the [contribution guidlines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown).

Thanks!

Closing pending test case

**Comment by meneldil** [comment]
Of course !
We can use it : https://jsfiddle.net/meneldil/scv15hh0/

**Comment by leggomuhgreggo** [comment]
Sweet, thanks for doing that.

#### Your sitch
If you can live without the second one sliding, a work around would be to use the `customPaging` method.

Also I bet you could set `pause` key to to `true` in the slick object on hover. 

Hope that helps.

#### Enhancement
I think we should tie it to `pauseOnHover` rather than `pauseOnDotsHover` because I can't see a way to determine which one would be the "dots"

I'm wondering whether the synced pausing should happen only when **both** slicks have `pauseOnHover`, or when either slicks have it. I can't think what use case that would call for only one to pause, and it's possibly semi-confusing to require both, but perhaps the flexibility is worth it.

I was a little surprised that when I hovered on the first slick, it did pause the second, but if I hovered on the second it wouldn't pause the first--wasn't sure why it would work one way and not the other, since I didn't think there was any hierarchy between the two. Fooled around a bit and figured out that hovering on the one that has `autoplay: true` will pause the other. Setting `autoplay: true` for both makes neither work.

**Comment by voodoodle** [comment]
Is there any update on this? Should I start another thread about this?

I don't understand how the "custom paging" method mentioned above would work - can you point me in the right direction?

IMHO - I definitely think that the default behavior for pauseOnHover should be to pause all synced sliders when any of them are hovered.

Thanks for a fantastic slider, btw.

**Comment by richardwiggins** [comment]
Any updates on this, I'm having issues with pauseOnHover and asNavFor?

**Comment by sajnayoosuf** [comment]
Hi @richardwiggins,
We can use following method to reset the slick option settings once execute the slider for first time.

$('.slider').on('mouseover',function() {
	$('.promo-slick').slick('slickSetOption', {'asNavFor': null}, false);
});

Thanks

**Comment by anmol950915** [comment]
Here is the working solution to this problem finally - 
If in case you want autoplay to stop when you hover around the slider-nav carousel is below .You can modify it to stop autoplay on hover around the slider-for as well. Once you remove your mouse from the hover area of the carousel section, autplay starts again.

$('.slider-nav').on('mouseover',function() {
$('.slider-nav').slick('slickSetOption', { autoplay: false }, true);
$('.slider-for').slick('slickSetOption', { autoplay: false }, true);
});

$('.slider-nav').on('mouseout',function() {
$('.slider-nav').slick('slickSetOption', { autoplay: true }, true);
$('.slider-for').slick('slickSetOption', { autoplay: true }, true);
});

https://jsfiddle.net/anmol950915/tjmb1swe/40/
