### ISSUE TITLE
Full width slider on large viewport

### ISSUE THREAD

**Issue by shourya23** [kenwheeler/slick#2498]
Short Description

When a full width slider is used on very large viewport i.e 1900px. The carousel breaks if infinite is set to true. The following settings are used: 

centerMode: true,
centerPadding: '150px',
adaptiveHeight: false,
slidesToShow: 2,
autoplay: true,
autoplaySpeed: 2000

#### Steps to reproduce the problem

1. Create a full screen image/text carousel with  above settings
2. View on screen of around 1900px vieport. 
3. Observe carousel behavior once all slides are complete and it has to reset. to initial slide.

What is the expected behaviour?
It should Ideally behave the same way as it does on normal laptop viewport of 1440px.

- Which browsers/versions does it happen on?
   **All Browsers**
- Which jQuery/Slick version are you using?
   **Slick - 1.6.0
   jQuery - 1.11.2**
- Did this work before?
  **No**

**Comment by leggomuhgreggo** [comment]
Hey @shourya23 can you make a reduced test case? There's a jsfiddle you can fork from the [contribution guidlines](https://github.com/kenwheeler/slick/blob/master/CONTRIBUTING.markdown).

I suspect your issue has something to do with the environment since what you're describing seems like a fairly common use case, but it's possible there's some idiosyncrasy that makes it bug out.

Thanks!

Closing pending test case
