### ISSUE TITLE
slider rinitialise (refresh) not possible 

### ISSUE THREAD

**Issue by rijosh** [kenwheeler/slick#2551]
> short description of the bug / issue, provide more detail below.

How can i load slick slider inside a tab, i want load image slider with thubnails inside a jquery tab. please help.  if possible give me a demo...

http://codepen.io/Rijosh/pen/GjxAkP

in fourth tab i have added a slick slider.  which one not working. if i load it in first tab it is working
====================================================================

###### `[  http://codepen.io/Rijosh/pen/GjxAkP  ]`  

use this jsfiddle to reproduce your bug: 
http://jsfiddle.net/simeydotme/fmo50w7n/ 
we will likely close your issue without it.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

...  

====================================================================

#### What is observed behaviour?

...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using?
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Hey if you search the issue history you'll find some longer conversations on this subject. The method I prefer is changing the tab styles to use `visibility: hidden` and `postions: absolute` instead of `display: none`, which prevents slick from getting a read slider dimensions. Alternatively you could fire the setPosition method on a tab shown event callback. Hope this helps
