### ISSUE TITLE
Lazy loading is not completely lazy

### ISSUE THREAD

**Issue by danwie** [kenwheeler/slick#2733]
Lazy loading is only lazy when it comes to not loading images that are not visible within carousels. But if the whole carousel is not visible (because you need to scroll down to see it) then it is not lazy. It would be better if only images that are actually visible to the eye gets loaded.

====================================================================

###### `[  paste your jsfiddle link here  ]`  

In the example at http://kenwheeler.github.io/slick/ you can see that lazyfonz1.png, lazyfonz2.png and lazyfonz3.png is loaded directly - even though they are not visible until scrolling down.

====================================================================

#### Steps to reproduce the problem

1. ...  
2. ...  

====================================================================

#### What is the expected behaviour?

I would expect lazyfonz1.png, lazyfonz2.png and lazyfonz3.png in the example is not loaded directly if lazy loading is on.

**Comment by franzos** [comment]
@danwie I always assumed this happens by design. In any case, I usually go with 'progressive'. It appears to work better with slow internet, as the user won't need to wait for the individual images to show up.

**Comment by simeydotme** [comment]
thanks @danwie for your request / suggestion 😃 
I would, however, say that this is a page/app level feature you're referring to, not a component-level feature.

The component (carousel) should handle its internal lazyness (images in the carousel), and as for determining if a carousel is loaded or not should be part of the page/app's job.

Having code written in a plugin/component which modifies or hijacks the behaviour of your page/app is not ideal at all, and could be problematic in many scenarios; especially since the kind of code needed for viewport-peeping is pretty intense, sometimes buggy and often egregious.

**Comment by danwie** [comment]
Thank you for your reply. You are absolutely correct. I didn't think this through.

Do you have any recommendation of how to load a carousel only when visible on screen? Even though it should not be a part of slick, you will need some knowledge about how slick works in order to get it working. I've been trying other popular compontents to handle lazy loading but they are not compatible with slick. Example: https://github.com/verlok/lazyload

**Comment by simeydotme** [comment]
the theory would be : 
- _not_ load slick at page load
- hide all slides except the first for every carousel
- get the viewport position at load
- initialise slick for any carousels in viewport
- get viewport on scroll
- initialise slick for any carousels in viewport

there's a million ways to do it, but this is not the place for code-help :)

Best, Si.

**Comment by mafudelaptu** [comment]
Here is an example of init a slick-slider if it gets in viewport via IntersectionObserver API:

[Codepen: Slick-Slider IntersectionObserver](https://codepen.io/mafudelaptu/pen/PoGrgQP)
