### ISSUE TITLE
Linking to particular slide index from external URL

### ISSUE THREAD

**Issue by creativearc** [kenwheeler/slick#2752]
Could a link be created such that slick would advance the slider to a particular index? Such as:

http://example.com/slide?index=8

**Comment by lhpderckx** [comment]
Hi creativearc,

Your URL will actually trigger a server request. Within this request handler, make sure you set the "initialSlide" option in your output.

Example: when using .Net MVC, make sure the View you render will set the initialSlide option either within the .slick() initializer:
```
$('.slicker').slick({
  initialSlide: 8,
  <your_other_options>
});

```
Or - and that's what I prefer - to place it in the slick data attribute, so you don't have to place the variable within your javascript that you have probably separated in a .js or .min.js:
(html)
`<div class="slicker" data-slick='{ "initialSlide": 8 }'>all my slides</div>`

I even took this one step further in one my .Net MVC projects and added "slick presenter" behaviour to my (partial) view models that should render a slick-slider. I can set options like 'centerMode', 'slidesToShow', 'centerPadding' and 'initialSlide' and then call its SlickDataAttribute() method from within the view that returns me a System.Web.HtmlString:
(html)
`<div class="slicker" @Model.SlickDataAttribute()>all my slides</div>`

Good luck

**Comment by simeydotme** [comment]
thanks @lhpderckx 

https://github.com/kenwheeler/slick/issues/152#issuecomment-233948114
^^ this is a JS way to achieve it.

**Comment by lhpderckx** [comment]
@simeydotme 
You're right that you can use the slick function 'gotoSlide' for that, but for sake of clarity and good practice:
- Handle query string parameters server side. Don't go parsing your url client-side, because maybe in about three months someone else or perhaps yourself changes the url to http://example.com/slide/8 and you wonder why it's no longer working.
- If you wish to use 'gotoSlide' by means of an url, try to respond to the url hash #, like http://example.com/pagewithslides#slide4. You may also use in-page hyperlinks to select a particular slide like that. I just googled it and I believe there are ways to do that, but I don't have a readily available solution here.

Maybe that'd actually be a nice feature for slick, to incorporate #-behaviour so you can bookmark each slide and use hyperlinks and urls to display an initial slide by url.
