### ISSUE TITLE
Centermode without infinite leaves gap left of first slide

### ISSUE THREAD

**Issue by ZNS** [kenwheeler/slick#2808]
> short description of the bug / issue, provide more detail below.

When using centermode and setting infinite to false. The first slide is also centered (inside the slider) leaving an empty gap to the left. I'm assuming this is the expected behaviour but I'd suggest that the first (and last actually) slide is not centered. So that we don't get empty gaps.

====================================================================

###### `[  paste your jsfiddle link here  ]`  
http://jsfiddle.net/4e8u0gcj/

====================================================================

#### Steps to reproduce the problem

Create a slider with centermode:true and infinite:false

====================================================================

**Comment by leggomuhgreggo** [comment]
Center mode is intended to be used with infinite, and I'm not sure there's a sensible use case for non-infinite, but perhaps you can shed some light -- consider that if part of a "previous" slide was visible, users would have an expectation that it could be navigated to. Let me know if there's something I'm overlooking in my thought process.

**Comment by mgntrn** [comment]
I've been looking for several hours to find a 'fix' for this. When I set the slider to `infinite` it's unclear to the (lazy) users that there are only 6 (or 5 or 4) items. They keep swiping and realize they've seen the same items when they've already seen them three or four times. So I'd like to disable infinite without wasting so much space on the left side of the first slide. I've tried to accomplish this with CSS and/or JavaScript btu without any luck due to breakpoint problems.

I'm not sure if more people are interested in a setting to move the first slide to the left, but if someone knows how to accomplish this I'm a happy man.

**Comment by mgntrn** [comment]
Here are two examples (Airbnb and Spotify) of what I'm trying to accomplish, both sliders are non-infinite. The Spotify slider has no 'stops' (number of slides to scroll), so the behavior of the Airbnb slider is more like that of Slick.

![img_4249](https://cloud.githubusercontent.com/assets/4264767/25445003/53b3e692-2aad-11e7-9c56-ad736b970b54.png)
![img_4251](https://cloud.githubusercontent.com/assets/4264767/25445004/53c684f0-2aad-11e7-96f3-0946841ff394.png)
![img_4250](https://cloud.githubusercontent.com/assets/4264767/25445007/5bad7804-2aad-11e7-8b1f-86af83ca2458.png)

**Comment by dfusionTownsend** [comment]
> Center mode is intended to be used with infinite, and I'm not sure there's a sensible use case for non-infinite, but perhaps you can shed some light -- consider that if part of a "previous" slide was visible, users would have an expectation that it could be navigated to. Let me know if there's something I'm overlooking in my thought process.

![carousel-peak-example](https://user-images.githubusercontent.com/29864918/63161181-55562300-c017-11e9-8436-b8e3413f65e9.gif)

The first slide would have no previous. I guess you could call it peeking into the next slide if there is one. This is ideal for the user because no arrows are required for touch due to the peek and also as @mgntrn was saying, it enables the user to understand when all content has finished being viewed rather than an annoying realisation for the user that you have just doubled back on yourself.

**Comment by d-packs** [comment]
Slick is a huge asset, but the lack of this behaviour is indeed a dealbreaker for modern projects.

**Comment by vuletiki** [comment]
I has same issue and trying with this
https://codesandbox.io/p/sandbox/jn8dmw
![Screenshot 2024-10-15 at 04 41 17](https://github.com/user-attachments/assets/c5cde39e-b39a-4ac9-a8f7-fc23eb299eee)
