### ISSUE TITLE
Slider set to display:none then set to show() ... first slide does not show??

### ISSUE THREAD

**Issue by pfar54** [kenwheeler/slick#2820]
I have read similar threads on here that have the issue of the first slide not displaying. I have tried to implement them into my example, but not appear to work.

I show the slider by clicking the trigger button.

====================================================================

https://jsfiddle.net/ndzf7gx6/1/

**Comment by leggomuhgreggo** [comment]
There're a bunch of issues that address this. Basically slick can calc the dimensions if the slides aren't taking up space in the dom. Use `visibility: hidden` w/ `position: absolute` to take it out of the document flow, instead of `display: none` or use the slick reset/setPosition method in your JS when the click event reveals it.
