### ISSUE TITLE
Unable to get Tall images to shrink to viewport

### ISSUE THREAD

**Issue by stljeff1** [kenwheeler/slick#3022]
> short description of the bug / issue, provide more detail below.

I do not understand how to get a tell image to shrink and fit a viewport.

###### `[  http://jsfiddle.net/z2fas8vb/  ]`  

use this jsfiddle to reproduce your bug: 

Essentially, here:
http://jsfiddle.net/z2fas8vb/

I have a slider that is populated by an end user. I am curious to know if I can make the Slick Slider  be flexible enough to handle differing heights and widths.

Because of other content below the slider, I have to put a max-height on the slider-s container. I would expect the images in slider to shrink to the constraints of the viewport, but I am not understanding how to do that.

#### Steps to reproduce the problem

1. tried various options like adaptiveHeight, mobileFirst, variable widths.
2. Researched other "issues" with similar inquiries, but cannot make sense of any solutions.
3. Tried width:auto; height: 100%; on images, to no avail.

I'm a decent front end dev guy, but i guess my brain is fried because I can't make sense of this issue..... If this is an "ID 10-T" error, let me know ;)

====================================================================

#### What is the expected behaviour?

The image fits the viewport. there is no overflow, and slick-slider remains same height

====================================================================

#### What is observed behaviour?

The image shrinks to  the width of the viewport,  but not the height. This leaves tall images being cut off.
...  

====================================================================

#### More Details

- Which browsers/versions does it happen on?
- Which jQuery/Slick version are you using? latest
- Did this work before?

**Comment by leggomuhgreggo** [comment]
Your demo doesn't really illustrate the issue, but there are a couple of options for containing an image by it's height.

The easiest is to call the image URI as a `background-image`, say in a style attribute on the slide, and then set `background-size: cover or contain` and probably `background-position: center center`

There's [this](https://codepen.io/leggomuhgreggo/pen/WExGem?editors=0100) method, but it will break if both the width and the height exceed the containing element's dimensions. Only works to contain the image at a single dimension, and will squish the image otherwise.

The other option is to use JS to set the image dimensions. I've used [this library](https://github.com/gestixi/image-scale) before, but the code to write it yourself isn't terribly complicated. You'll want to run it after slick has initialized.

**Comment by stljeff1** [comment]
@leggomuhgreggo  My apologies. I am new to jsFiddle and didn't realize i needed to specifically click 'Save' to generate a new fiddle.

here is the right link.

http://jsfiddle.net/stljeff1/eaqq8jd0/


I though about the background image technique. My only objection is the lack of image tags, and its effect on the SEO value of the page. I'd like to stick the current html structure if possible.

I just started using flexbox (ie: display: flex). I'm still fuzzy on how it works, but could I use that?

**Comment by leggomuhgreggo** [comment]
You can use `display: flex;` on the parent element that's restricting the dimensions and `max-width/height` the images (see pen in previous comment), but, as I say, this doesn't totally fulfill the contain functionality, because if both an image's height and width exceed the restricting view's dimensions then it will squish.

**Comment by stljeff1** [comment]
I don't mean to argue, but i find it hard to believe there is not a way to say `img {width: auto; height: 100%; } and have the image stay within the bounds of the box. 

I only question it because its driving me nuts and I'm borderline obsessing.

**Comment by leggomuhgreggo** [comment]
You know I might be wrong about it squishing using the max-width/height 100% technique. See here: https://codepen.io/leggomuhgreggo/pen/WExGem?editors=0100

**Comment by stljeff1** [comment]
Ah, ya, I see. Neat.

Thanks for helping me work this out. Based on what you provided, I tweaked it a bit to get after what I wanted initially.

see here: http://jsfiddle.net/stljeff1/eaqq8jd0/1/

I moved the max-height of the container the .slick-list element. If it goes any higher in the Dom, then the dots and slide navigation disappear since by default, they appear outside the slide container. 


And for the sake of documentation, if you can assume all images have the same width:height ratio, then you could use the padding-bottom trick and force the slide container to that ratio.

**Comment by leggomuhgreggo** [comment]
Glad it helped!

I think using the padding bottom AKA intrinsic ratio technique would only constrain the landscape images.
