### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sanfeijoo** [kenwheeler/slick#3067]
Hi @kenwheeler can you make a new release. Thanks.

**Comment by 1de** [comment]
@kenwheeler yes, a new release would be really nice. in reference to #3032, i've got that issue. long story short: i've compared the files on http://kenwheeler.github.io/slick/ with the latest release-version (e.g. from bower). the version numbers are the same (1.7.1) but the code differs. happy to know, but ugly to find :-)

thank you in advance

**Comment by 1de** [comment]
or do we may have to mention @leggomuhgreggo ? :)

**Comment by leggomuhgreggo** [comment]
Should be updated to 1.8.0. Let me know if you find anything I missed. Thanks!

**Comment by smile-monkey** [comment]
Hi leggomuhgreggo!
how are you?
I read your all commits to solve my issue.
The issue is the browser jump with a scroll at the slick position.
The browser jump only occurs in Safari and firefox, not Chrome and IE.
I have already updated the slick.js to 1.8.0.
I think the reason is that Safari and firefox doesn't support the "scroll linked effect" property.
let me know the best way to solve the issue.
Regards.
