### ISSUE TITLE
"Responsive" option isn't being updated in slickSetOption

### ISSUE THREAD

**Issue by tylerpepper** [kenwheeler/slick#327]
I'm working some more on my Drupal module and was making an update function so that users can update a Slick instance in code if they need, and I noticed that even the most basic of responsive objects isn't working with slickSetOption. Might just be an oversight on my part, but I figured I'd post this here anyways. Below is an example of my code:

```
var key = 'responsive';
var fieldSettings = '[{
            breakpoint: 768,
            settings: {
              slidesToShow: 4,
              slidesToScroll: 4
            }
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 3
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 2,
              slidesToScroll: 2
            }
          }]';
$(target).slickSetOption(key, fieldSettings, true);
```

Any help would be greatly appreciated. Thanks!

**Comment by simeydotme** [comment]
@tylerpepper , @influxweb , @kenwheeler 
https://github.com/simeydotme/slick/commit/406da2cd9a1715a11f3b043a89de3e19afa3a272

It's been a long time since your pull request, @tylerpepper (#335) and the code-base has changed quite a bit. I also noticed that your pull wasn't really hitting some key areas. (as I clarify in the commit notes: https://github.com/simeydotme/slick/commit/406da2cd9a1715a11f3b043a89de3e19afa3a272 )

I have set up a pretty extensive demo to show it working solidly on initialisation and with options set post-init. http://jsfiddle.net/simeydotme/54a9d57t/ - it would be really great if you could help me test it :bow: :ok_woman:

**Comment by influxweb** [comment]
:+1: :clap:

**Comment by vijayaganth** [comment]
Hello ken,
when i reach that, then slick slider will play start from first frame!
what i do?
