### ISSUE TITLE
Can't scroll up and down on mobile over slick slider

### ISSUE THREAD

**Issue by GREGG-CHRISTOFFERSON** [kenwheeler/slick#3278]
Users can't scroll up or down over the divs with class of slick-track on Android

**Comment by ahmadalfy** [comment]
It's a common issue across scripts and widgets that use swipe (maps, sliders ... etc). My suggestion is to limit the height of the carousel from covering the whole screen or disable swiping if you can't limit the height. Also, some people leave a space on the sides of the carousel so that it doesn't occupy the whole width of the screen to give some room for the scrolling.

**Comment by notrealdev** [comment]
Using version 1.9.0
Same issue
