### ISSUE TITLE
Diagonal swipe issue at mobile

### ISSUE THREAD

**Issue by intransitorio** [kenwheeler/slick#3286]
#### Description

If the swipe is slightly diagonal the carousel don't slide.

====================================================================

http://jsfiddle.net/fmo50w7n/1718/ 

You can test using this example

====================================================================

#### Steps to reproduce the problem

1. using your mobile device try to slide the items doing a slightly diagonal swipe.

====================================================================

#### What is the expected behaviour?

The expected behaviour is to slide the carousel if the swipe is more horizontal (or vertical, depends on the settings) than vertical.

====================================================================

#### What is observed behaviour?

If the swipe is slightly in a diagonal direction the carousel don't slide it

====================================================================

#### More Details

- Can be tested on desktop chrome mobile view too;
- Tested on Android(chrome) and IOS(safari and chrome). same issue, but more notable on Android.

Thanks

**Comment by ahmadalfy** [comment]
I don't think it's an issue for now. Swiping should be either horizontal or vertical. Diagonal won't work.

**Comment by dianasotirova** [comment]
Hi,

I am experiencing the same issue. May be, it's too much to expect from the users to make straight horizontal line in order to swipe a slide. The problem is that slick assumes if the direction is slightly different from the slick direction the user is scrolling. You could increase the length for the vertical swipe check (now it is 4) or you could add a setting for this. Furthermore, my page is smaller than the screen so there are no scrollers on the document and scroll is not possible. You could add a check if scroller is present or at least add a setting. 

I will appreciate if you think about addintg settings at least.

Thanks

**Comment by intransitorio** [comment]
I tested it with the 1.6.0 version and it works perfectly even with the full diagonal swipe. PERFECT.
@dianasotirova try to downgrade it.

**Comment by rajaneeshgit** [comment]
@intransitorio Thanks for suggesting the version 1.6.0 (earlier using 1.8.0, facing problem with horizontal swipe, multiple times doing swipe for triggering swipe). Yes, It's working If you want to consider inclined or declined swipe as horizontal swipe. Coz its very difficult for users to swipe accurate horizontal in straight line sometimes.

**Comment by jolugama** [comment]
Yes, the 1.8.0 in android is not working if you swipe diagonal, but version 1.6.0 is ok!!!. 1.6.0 es better!.

**Comment by thepotoo** [comment]
@ahmadalfy can we reopen this?  1.6.0 is dramatically better on mobile, swipes don't work half the time on mobile in 1.9.0.

**Comment by carybriel** [comment]
Replacing "Slick.prototype.swipeMove" in 1.8.0 with the 1.6.0 function improved the flaky horizontal swipe issues introduced > 1.6 for me, and it didn't appear to break anything related to horizontal swiping. At least, nothing I've noticed yet. It may break a vertical swipe application. Not sure. I didn't test that, because my requirements for this application are horizontal. But diff the two functions to see the changes and get an idea of what was trying to be accomplished.
