### ISSUE TITLE
Pause on interaction

### ISSUE THREAD

**Issue by zslabs** [kenwheeler/slick#370]
If we have the form set to autoPlay, interacting with the form (via the arrows or dots) should  give us the option to turn off that autoPlay, as the user has interrupted the flow of the slider and can manually control. I'm currently using keyboard navigation and it'd be nice to be able to stop the autoPlay from continuing:

```
$(document).keydown(function(e){
    // left
    if (e.keyCode == 37) {
        $listingGallery.slickPrev();
        return false;
    }
    // right
    if (e.keyCode == 39) {
        $listingGallery.slickNext();
        return false;
    }
});
```

**Comment by swinggraphics** [comment]
The slickPause() method does not work if pauseOnHover is true; the slider will start up again later.

It would be great to have an option like `pauseOnHover` — "pauseOnInteraction". When the slider is clicked anywhere or a slide is changed by any means, all autoplay stops permanently. Every time I create a new site with Slick, I have to hunt down code I've used in the past to fake this, and it never seems to work correctly without troubleshooting. It always starts up again when the window loses focus, or the slider loses focus, or the mouse moves away…

The rationale is that once the user starts interacting with the slider, they don't want that control wrested away from them. "Damn it, I clicked the previous slide arrow because I hadn't finished reading it, and now it's gone again!" That kind of thing.
