### ISSUE TITLE
show and hide slickslider when clicking on buttons

### ISSUE THREAD

**Issue by inzonet** [kenwheeler/slick#3767]
> short description of the bug / issue, provide more detail below.

====================================================================
It's not working properly when I hide it on page loading.

###### `[  paste your jsfiddle link here  ]`  

https://jsfiddle.net/Chae/pb8kyx0q/33/

====================================================================

#### What is the expected behaviour?

I like to show and hide a selected slider when I click on the button.
it's working when I show all multiple sliders on a page. but it's not working fine when I hide them at first using css ( display: none)

See the jsfiddle shown above.. if you decomment .slider class. no sliders show on loading. And click on the button, nothing shows..  

====================================================================

#### What is observed behaviour?

...  

===============================================================

**Comment by ahmadalfy** [comment]
It is working properly. The sliders need to be visible in time of initialization to properly calculate the dimensions. Otherwise it calculates the dimension of the slider as zero and it doesn’t work as you reported.

The solution to this is either delay initialization of the carousel till it is visible or to `unslick` the initialize it again when it becomes visible.
