### ISSUE TITLE
jquery ui draggable in new item

### ISSUE THREAD

**Issue by chuss424** [kenwheeler/slick#3789]
Hello, I am trying to use jquery ui draggable in the slick slider however, in the new article the stoppropagation does not work, could you please help me?

this is the demo

http://jsfiddle.net/jonqz0m3/

**Comment by ahmadalfy** [comment]
This is because the jQuery UI draggable isn’t initialized on the newly added slide. You need to initialize it. I successfully did but dragging the new draggable item would drag the whole slider. I suggest you disable the `draggable` option because it’s complex and not use friendly. Use arrows or bullets instead. Having 2 draggable items one inside the other and having them to behave differently doesn’t make sense.
