### ISSUE TITLE
Issues using with Foundation 5's interchange responsive content images

### ISSUE THREAD

**Issue by eablokker** [kenwheeler/slick#424]
Foundation 5 recommends using slick-slide instead of their own deprecated orbit-slider.

When using Foundation 5's interchange responsive content images in a slick slide, somehow the image does not appear in the very last slide.

When transitioning from the last slide and looping forwards to the first slide, the interchange image doesn't show up until the slide finishes animating in.

When transitioning from the first slide backwards to the last slide, the interchange image does appear during the animation, then disappears when the animation finishes sliding in.

**Comment by senlin** [comment]
I don't understand why this issue is closed both here and on [Foundation](https://github.com/zurb/foundation/issues/5714). It seems far from solved.

Is there now a consensus that Interchange cannot be used with Slick?

What's the alternative? 
Loading a series of giant images in a slider on tiny screens?
Use an alternative like [Mobile Detect](http://mobiledetect.net/)?

**Comment by kenwheeler** [comment]
@senlin Have you tried this with Picturefill?

**Comment by senlin** [comment]
@kenwheeler no I haven't. I had to Google picturefill to see what it is.

I resorted to using MobileDetect with less image-sizes, but works fine.

**Comment by MP3en** [comment]
https://github.com/zurb/foundation/issues/5714

**Comment by MP3en** [comment]
https://github.com/zurb/foundation/issues/6507
