### ISSUE TITLE
Problem with "draggable: false" and "swipe"

### ISSUE THREAD

**Issue by Leolik** [kenwheeler/slick#458]
After I set `draggable: false` for desktops, `swipe: true` stop working on touch devices.

1.3.7 - bug reproduced
1.3.6 - bug not reproduced

**Comment by ccconsulting** [comment]
Hi, I'm on Version 1.5.9 and I'm having problems with draggable on desktop still dragging after set to false.  Anything I'm doing wrong?

$('.services-slides').slick({
		autoplay: 'false',
		draggable: 'false',
		swipe: 'false',
		prevArrow: $('.prev-arrow'),
		nextArrow: $('.next-arrow'),
		dots: 'false'
	});

Thanks

**Comment by LEEYONGCEIH** [comment]
Guy i have a problem with the slick slider,any help is appreciated.

Problem is here - http://stackoverflow.com/questions/37202929/my-slick-slider-is-not-working-when-i-toggle-with-2-image-button

**Comment by Ram-SR** [comment]
`draggable: false` not working in desktop and the slick version is 1.8.1

**Comment by Pamblam** [comment]
i was having problems with the swipe-to-slide function not working on android and this was the most relevant looking thread i found. turns out it was related to ADB. unplugging my phone from the computer fixed it and plugging it back in broke it. 

just thought i'd leave a note in case anyone else was having a similar issue.
