### ISSUE TITLE
Going from first to last slide, or from last to first slide, on infinite mode doesn't animate

### ISSUE THREAD

**Issue by miguelleite** [kenwheeler/slick#463]
Hey there.
In my solution, I wanted the next/previous slides to have a scale of 75%, and the centered one with 100% scale.

I'm using the following settings:

```
$('#slick-carousel').slick({
        autoplay: true,
        arrows: false,
        centerMode: true,
        dots: true,
        slidesToShow: 1,
        centerPadding: '295px',
        infinite: true
});
```

In my CSS I have the following:

```
#slick-carousel .slick-slide.slick-active.slick-center {
        -webkit-transform: scale(1);
        -ms-transform: scale(1);
        -o-transform: scale(1);
        transform: scale(1);
}
#slick-carousel .slick-slide {
        -webkit-transform: scale(0.75);
        -ms-transform: scale(0.75);
        -o-transform: scale(0.75);
        transform: scale(0.75);
        -webkit-transition: all .3s linear;
        -o-transition: all .3s linear;
        transition: all .3s linear;
}
```

It works great, unless when I slide from last to first slide, or from the first to last slide. Any thoughts on that? I'd appreciate any help.

Thanks in advance.

**Comment by nickmelville** [comment]
Not a fix, but a workaround...  targeting `.slick-center` for the transition/animation works if you have `centerMode:true` enabled:

http://jsfiddle.net/1wyegw6L/

The issue is that when it "wraps" around, it is showing the cloned item first, and then changing the `translate` value to show the original, without ever applying the `slick-active` class to the cloned item.  `slick-center` does get applied to both though.

**Comment by bbodien** [comment]
This doesn't seem to be fixed in 1.6.0 yet. 

As @nickmelville described, when transitioning from the first or last slide to the cloned one on an infinite Slick slider, the `slick-active` class isn't applied to the clone.

It feels wrong having to resort to `centerMode: true` to work around the problem.

**Comment by omzy83** [comment]
+1. Any update on this?

**Comment by binarytrance** [comment]
+1 Looking for an update to this.

**Comment by eugeneAamplify** [comment]
No luck from my side either :(

**Comment by aaronransley** [comment]
+1 running into this issue as well. Attempting to use `centerMode: true`, but even when targeting the `.slick-center` class, transition pops remain.

**Comment by chrisandrewcl** [comment]
First, thanks @kenwheeler for this awesome piece of work!

For those of you who are still facing this issue in the 1.8.0 version, I was able to get rid of it by downgrading to 1.6.0.

**Comment by prozhkov** [comment]
@chrisandrewcl Thanks a lot

**Comment by rbrlortie** [comment]
Still having the issue with centerMode. Any solution that doesn't require downgrading?

**Comment by tfadz** [comment]
> First, thanks @kenwheeler for this awesome piece of work!
> 
> For those of you who are still facing this issue in the 1.8.0 version, I was able to get rid of it by downgrading to 1.6.0.

**Comment by tfadz** [comment]
This doesn't fix it still.

**Comment by y1n0** [comment]
I'm still facing this issue even after downgrading to 1.6, setting centerMode and targeting centered slide with `.slick-center`
