### ISSUE TITLE
Slick with highcharts

### ISSUE THREAD

**Issue by Leothorn** [kenwheeler/slick#525]
Is there a way of putting active highcharts as a part of the carousel ?

**Comment by renatalucia** [comment]
Any news on this topic? I could put highcharts on the slick carousel. But facing problems to use centerMode.

**Comment by ahmadalfy** [comment]
Please create a fiddle demonstrating the problem

**Comment by renatalucia** [comment]
Here is the fiddle:
https://jsfiddle.net/gvwtfy7g/3/

Please note that the chart on slide 7 (the last one), which is on the left side of the "first" slide, is not visible, although it's title is. Same happens when you swipe until the end: the chart on the "first" slide is not visible.

I would appreciate any idea about how to solve this problem :)
