### ISSUE TITLE
Swiping iframes (eg. YouTube video) doesn't work

### ISSUE THREAD

**Issue by denvers** [kenwheeler/slick#564]
The touch(start|move|end|cancel) events aren't working on iframes, such as a YouTube video. 

It seems the way attaching touch-events on iframes are a bit different. See http://smithamilli.com/blog/touchstart-on-iframes/

**Comment by shkodasv** [comment]
Is there any progress?

**Comment by kenwheeler** [comment]
Closing and recommending @thinsoldier 's approach. There is very little you can do about this, its an IOS issue.

**Comment by thinsoldier** [comment]
What I do (and I've had to do it with *every* slideshow I've ever used) is to show an image pulled from the video initially, then when that is clicked I replace it with the iframe.

**Comment by Leapfrognz** [comment]
Please note if you use the placeholder + icon approach suggested by @thinsoldier, then the video youtube view counts will not be registered. Apparently only native iframe buttons work.

**Comment by kristojorg** [comment]
Alternatively, you can absolute position a transparent cover over the iframe until it is clicked, and play the video on click.

**Comment by stratboy** [comment]
In my opinion, none of the suggested workarounds really work, except keeping the dots/arrows visible.
The image/cover way, would work well until you tap on it and the iframe is created. Then, the issue would be back: you couldn't drag the slideshow anymore from there. I'm quite suprised @kenwheeler didn't noticed this drawback when recommending @thinsoldier solution. On @thinsoldier's gist's comments though, there's some code from 'aiphee' user that could help, but I didn't tested yet.

**Comment by thinsoldier** [comment]
Since that 2014 comment on that gist I've had 3 projects where the client insisted that the youtube video NOT stop playing even after switching to another slide. So I don't think it would be a good idea to add any youtube-iframe-specific code like aiphee's https://gist.github.com/zigotica/4438876#gistcomment-1451911 to Slick because one size does not fit all scenarios and you'd have to add more and more options just for youtube and then vimeo and then pornhub or whatever else.

A cookbook of solutions to common problems would be good to have though.
