### ISSUE TITLE
Inline arrows

### ISSUE THREAD

**Issue by ghost** [kenwheeler/slick#577]
It is possible to have arrows and dots like on this picture?

![slick](https://cloud.githubusercontent.com/assets/1485693/4489386/8367226c-4a1a-11e4-9337-e39f0947266d.png)

The number of dots is dynamic.
It should behave like inline elements or inline-block and be centered to carousel area.
I don't know how both arrows and dots insert into one parent element and the functionality will remain the same.

**Comment by julianxhokaxhiu** [comment]
This is working ONLY if we have one slider in the page. What if we have two or more?

I think that `appendArrows` should be also a callback that as arguments have the current slick istance so we can append something when we want (after the slick element have been initialized) RELATIVE to the current istance.

Otherwise you would get in the same container ( like `.slider-nav` ) Nth time the arrows and dots * numbers of slick sliders in the page. Practically because `appendArrows` is not having any "relative context", it will be appended to any slick slider visibile on the page.

**Comment by martinkovac** [comment]
Just use
`$('.slider-container').each(function() { ... })`
for example.

**Comment by martinkovac** [comment]
I have update your example: http://jsbin.com/dimozi/1/edit?html,js,output

**Comment by knightkiddo** [comment]
Hi,
I was looking for this solution but it doesn't work anymore with slick 1.5 and slick 1.5.5.
It's ok with 1.4 but I need last version for my project... someone can help ?
regards

**Comment by CREEATION** [comment]
:+1: :(

**Comment by gabrieldrummer** [comment]
Hi,
I know topic was closed long time ago, but I got problem with solution developed by martinkovac. Martinkovac would You make a working example on fiddle or codepen?

**Comment by shajad1234** [comment]
it is possible in react  ??

**Comment by 0ll0lll** [comment]
hey, 
in react you can do the following: 
- set arrows to false in the settings objects
- use appendDots and add your custom arrows around the dots ul
- in your custom arrows add slickNext() and slickPrev() methods on click
