### ISSUE TITLE
Make slide clickable

### ISSUE THREAD

**Issue by tonyellow** [kenwheeler/slick#608]
Hi,

First of all thank you for this great script. This is probably a very stupid question but I can't seem to figure out how to make a slide clickable.

This is my html:

```
<div class="logoSlider">
    <div><a href="http://www.test.nl" target="_blank"><img src="/img/logo.png"></a></div>
    <div><a href="http://www.test.nl" target="_blank"><img src="/img/logo.png"></a></div>
    <div><a href="http://www.test.nl" target="_blank"><img src="/img/logo.png"></a></div>
</div>
```

And this my javascript:

$('.logoSlider').slick({
  dots: false,
  infinite: true,
  speed: 300,
  slidesToShow: 3,
  slidesToScroll: 1,
  autoplay: true
});

Whenever I click a slide the caroussel advances to the next item. I can't seem to disable this and just make my slides clickable.

Hope someone can help.

Thank in advance,

Anthony

**Comment by Togotooner** [comment]
Tony,..did you ever find a solution to this??? Exactly what did you do to allow a slide in the carousel to be clickable??????

**Comment by iamrishirb** [comment]
@tonyellow instead of wrapping them in a div container and then adding markup for <a href="something"><img src="something"/></a>, we can directly make the containing anchor tag is wrapper and replace <div> by <a href="anywhere you want to link your slide"><img></a>.

No extra styles of JS. It solved for me.
