### ISSUE TITLE
.slick-cloned and dynamic content change

### ISSUE THREAD

**Issue by LostSenSS** [kenwheeler/slick#628]
Hi!

As I understand, ".slick-cloned" is generated and saved during the initialization of the slider. 
Is it possible to dynamically update and save new content into ".slick-cloned"?
Because if slider content is changed after initialization ".slick-cloned" contain stale data.

**Comment by kenkogi** [comment]
Hey @kenwheeler,

First of all, thank you so much for creating this. It's one magical carousel that fits any project I have. 

Since slick is the one creating the clones, is it not up to slick to keep them synced? I would be delighted to spend some time in investigating a way to do this and create a pull request if you'll accept one. 

Is this something anyone else is interested in?

**Comment by MateoLa** [comment]
Hi kenkogi. I am.
I had invested about a month trying to use different sliders with inputs (change slide imgs src when image input change).
First I tryed with bootstrap carousel, then with flexslider and now i'm trying to use slick.
I'm going to try to follow kenwheeler recomendation but I'm not an expert in javascript.
Thanks, Mateo.
