### ISSUE TITLE
Lazy load images in responsive settings not working unless used lazyLoad: 'progressive'

### ISSUE THREAD

**Issue by mgalic** [kenwheeler/slick#668]
It doesn't cycle properly after the last slide, demo: http://jsbin.com/loxunu/2/edit?html,js,output
Only when I added 'progressive' mode to load images, it was showing up. You should put that somewhere in documentation.
Otherwise, great plugin.

**Comment by kenwheeler** [comment]
This is because the clone index hadn't been hit yet. Its an unfortunate side effect of clones that I hope to resolve in the future.

**Comment by melior88** [comment]
Have you manage to find a solution for this bug??

**Comment by reflex84** [comment]
@kenwheeler buddy! First off, great plugin and after extensive testing with other similar plugins, I found yours the best for various reasons. However have you been able to conquer the Lazy Load onDemand feature? My images do not display (like their invisible) when I use onDemand, whereas progressive works fine. My worry about "progressive" is this comment made on SO:

http://stackoverflow.com/questions/25726554/lazy-loading-progressive-vs-on-demand

"Be careful cause progressive is not supported in all Safari browser (tested on Slick 1.5.5, 1.5)"

Is there no way to snoop at other similar plugins and check how they've done it (not sure if others have the same problem)?

Of course it would be great to have the feature working ... otherwise and nevertheless, thanks for a superb plugin!

**Comment by CREEATION** [comment]
@kenwheeler This is still a thing, especially the bug regarding Safari browsers. Using latest `1.5.9`.

**Comment by mcclaskiem** [comment]
@kenwheeler I am having a somewhat similar issue only reversed. When `lazyLoad` is set to `ondemand` and the slide count = slidesToShow the images never get loaded.

```
$designerSlick.slick({
    dots: true,
    infinite: true,
    speed: 750,
    adaptiveHeight: true,
    slidesToShow: 4,
    slidesToScroll: 4,
    responsive: [
        {
            breakpoint:950,
            settings: {
                slidesToShow: 2,
                slidesToScroll: 2
            }
        },
        {
            breakpoint: 700,
            settings: {
                slidesToShow: 1,
                slidesToScroll: 1
            }
        }
    ]
});
```

Do I need to `unslick` at the 950 breakpoint and not use the carousel here? I would assume it would try and load all the images similar to `progressive` since they are all in view.

**Comment by jcairo** [comment]
Is the Safari issue with progressive loading still a problem with 1.6?
