### ISSUE TITLE
Support child <div> elements within each slide container <div>?

### ISSUE THREAD

**Issue by MichaelMarcialis** [kenwheeler/slick#81]
I'm using your slick.js script in the hopes of having each slide element contain any and all types of HTML content. In implementing your script, it appears that the use of any child `<div>` elements within the parent "slick-slide" `<div>` picks it up as yet another slide container, and renders it as such. Instead, I'm hoping to have any children `<div>` elements remain within the parent div container, and not treated as another slide.

For example, given the following markup:

```
<div class="drawer-carousel-group">
    <div class="drawer-carousel-item">
        <h1>test</h1>
        <div>more test</div>
    </div>
    <div class="drawer-carousel-item">
        <h1>test</h1>
        <div>more test</div>
    </div>
</div>
```

My expectation is that it would be generate two slides, each with a child `<h1>` and `<div>` within them. Instead, four slides are generated, because I assume the script is making all `<div>` elements into an individual slide container.

Is there a way to change the behavior to achieve this?

**Comment by janwidmer** [comment]
Hey..
is using nested divs in the slides supported in Version 1.6? It seems, that also the nested divs get picked up as a slide.. I am working on a legacy project and am not able to update to a newer one..
I have seen the slide option but since this option does not allow a wildcard selector like '> div' and I have a long list of classes which can be within the slide, it's kinda hard to specify this slide option

Any info would  be appreciated

**Comment by zeiv** [comment]
Looking for this functionality as well.  Is it present in the latest version?
