### ISSUE TITLE
Slick + mousewheel.js

### ISSUE THREAD

**Issue by iamstiil** [kenwheeler/slick#820]
http://jsfiddle.net/umv0Lz7k/

I tried to implement the mousewheel.js to enable scrolling inside of slick, but somehow i can't get it to work? is this caused by slick or mousewheel or have i coded it wrong?

**Comment by coderNik** [comment]
Hey dev guys, I am facing problem with slick with mousewheel, I want to detect whether the slider is reached to the end (last) slide and want to stop mousewheel feature after that, so that user can scroll down to entire page.. see this site and check mobile scroll option which is on second section http://org.servd.co.in/
