### ISSUE TITLE
Slick pushing content down page in Firefox

### ISSUE THREAD

**Issue by maxdeviant** [kenwheeler/slick#842]
Today I noticed some weird behavior in Firefox (34.0), where the content below the Slick container was being pushed way down the page.

After a little investigation, I noticed that by disabling Slick (and thus having the images in the carousel stack on top of each other down the page), the point where the content was being pushed to was where the images ended.

It seems like Firefox does not adjust the other elements when the carousel elements collapse down into the carousel, leaving them positioned further down the page.

I was able to fix this issue by adjusting the height of the Slick container after initialization:
```javascript
$('.slick-container').height(1);
```

Not sure if this qualifies as a bug, but I thought I may report it anyways, if for no other reason than helping someone else who encounters the same issue.

**Comment by davidpollet** [comment]
I solved my problem with progressive enhancement. :)
In first, i added a class display none on all slider's children except the first.
Second, i used jQuery removeClass for cancel the display none rule.

User with no JS don't see a broken layout and firefox catch anchor correctly.

**Comment by fourroses666** [comment]
This issue is still there. (FF OSX and WIN)
Is there an easy way to fix it? 
When refreshing the page the current scrolled position is way off.

**Comment by os1r1s110** [comment]
Similar problem happens to me on multiple browsers (chrome, firefox and edge all to their latest versions). 
When I load a page in which there is a slick carousel activated, the anchor position is always way off and always at the same place for all sections below the carousel.

**Comment by Zubru22** [comment]
Still having the same problems like others. After using anchor tag scrolling position gets off. I have two sliders which are triggered only on mobiles, the problem occurs only with the top one. If I comment out triggering first slider it scrolls as it should. Tried @davidpollet solution but none of that worked for me. Also I tried to use timeout but it only makes the bug appear later. Any ideas? It's been years since that issue was opened...

**Comment by a4aLien** [comment]
Still having the problem on a horizontal carousel. 
It skips the first <div>

I have 5 370px <divs>and the container for them, div.slick-track is 1850px wide, which is correct.
I only have to disable/enable the CSS rule on slick.css line-99:
.slick-initialized .slick-slide { display: block; }

Disabling/Enabling via inspect-element fixes the first slide *without refresh*.

Firefox vers. 53.0.3 (32-bit)

**Comment by vaibhavshah846** [comment]
For any one still struggling with this in 2019, we faced a similar issue with chrome stable release v76.
The root cause of our issue was not the slick slider but the way its container was positioned.
The container of the slick slider was positioned "absolutely" with only its "right" attribute specified.
The CSS:

```
.slick-container
{
 position: absolute,
 right: 0
}
```

This does not go well with the new version of Chrome and we need to specify at least two co-ordinates for an absolutely positioned element.
So adding a "top" attribute resolved it.

```
.slick-container
{
 position: absolute,
 right: 0,
 top: 0
}
```

Alternatively, position it relatively.

```
.slick-container
{
 position: relative,
}

```

**Comment by MRDesing** [comment]
I have created a carousel with Slick.js in Divi and am having this same problem with Firefox.

https://prnt.sc/11aq9xx

I have tried the solutions outlined here but I can't get it to work properly.
I have tried several Divi modules to make the carousel and with the Image and Blurb modules works correctly. But with the Portfolio and Blog modules, I get this bug in Firefox
