### ISSUE TITLE
Slick Carousel Crashes iPhone6

### ISSUE THREAD

**Issue by HaukeB** [kenwheeler/slick#854]
My team and I are trying to implement the Slick carousel in our project. It works splendidly on every device we have tested it on except for the iPhone 6. Not only does it not work but it actually causes the phone to turn off and restart! We have tested it on earlier versions of the iPhone and also on a couple of iPads and it works just fine. The only one having an issue with it is the 6. We checked and double checked that our JS and markup is well formed and we also checked if the culprit might be one of the carousel properties. So far no luck.

**Comment by maxfolley** [comment]
Hey guys, we're experiencing the same issue on 6+. Thought it was our source but commenting out this plugin resolved our issue.

**Comment by davidglivar** [comment]
I believe this line may be the culprit : https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L1091

Looks like its applying that event handler to all DOM objects.

With the line kept in the source, this is the number of listeners being added.

![kept](https://cloud.githubusercontent.com/assets/692152/6425064/4c0ca8e8-becb-11e4-8bc5-c1deb4d737ab.png)

When commenting out this line, we see the listeners drop.

![removed](https://cloud.githubusercontent.com/assets/692152/6425065/50860e50-becb-11e4-8fb4-16f1b08cddfa.png)

Resolved our issue with iPhone 6+

**Comment by kenwheeler** [comment]
Can you guys provide a reduced test case? That way I can know the exact conditions and profile it. I have a 6 and I've never seen this.

**Comment by simeydotme** [comment]
I can't help much with this bug, but I thought I'd chime in with some experience:

Not slick specific, but the company I work for has many problems on iPhone 6+... it seems the __memory management on the 6+ is total bollocks__ that or Safari has some major bug. Anyway, we continue to have problems all over our site due to some developer's flagrant use of delegated events from the document/body ... its a terrible practise and I'm currently trying to eradicate it... I hope that will fix the issue. It is exascerbated by zooming and rotating the screen.

It would be great if we can try to stamp it out of Slick, too :)

**Comment by kenwheeler** [comment]
@simeydotme Have you guys isolated some causes of crashes on the 6+?

**Comment by simeydotme** [comment]
Its generally massively delgated events (unbinding them stabilized the
site) from the document or body... And also resize events (but less so).
Our priority now is to reduce the delegated events. Removing the ability to
pinch-zoom the page helps (user scaling), too... But just reduces the time
it takes to crash, not fix completely.

It seems to be memory leakage in iPhone6+  ... Because after one browser
crash and reload, the crashing becomes more and more frequent until the
whole phone will restart.

Apart from the general knowledge that its coming from delegated events on
iPhone6+ only, i havent got much more information :(

Hope that helps.
Si.

**Comment by r4d1n** [comment]
I can say that after struggling with this for a few days that downgrading to Slick 1.5.8 fixes this issue beautifully.
