### ISSUE TITLE
Feature Request: Method to check if slick is loaded.

### ISSUE THREAD

**Issue by jimmymorris** [kenwheeler/slick#899]
I would really <3 a method to check if the slick slider is loaded or not.

**Comment by iainhenderson** [comment]
What do you mean by "slider is loaded"? - That the plugin has successfully loaded, or that all images in the slider have finished loading?

**Comment by jimmymorris** [comment]
Essentially, that a slick objected is created. It comes from the fact, Scenario would play out something like, I have a slick slider being initialized in a core block of a CMS. I have a separate theme for that CMS where I want to add on certain set of options and attributes specific to that theme. However, if I try to add an attribute before the slick slider is initialized it throws an error.

Hopefully that made sense.

**Comment by kenwheeler** [comment]
Every loaded slick has a class slick-initialized.

**Comment by mudisujit** [comment]
Hi @kenwheeler ,
By default my accordion is close when I click the accordion the slider look messed.  Any Idea?

**Comment by cameronjonesweb** [comment]
@mudisujit that's because when it initialises, the slider is hidden so it has no height. You can fix it by only initialising the slider once the accordion panel opens

**Comment by pangpronto** [comment]
พิมพ์  I want an ice cream, Send this to Thailand dan ma hussajan.

**Comment by gozarmanuariana** [comment]
Hi @kenwheeler,
 I want to override the width of the slick-slides and also make the slick container visible only when slick is in its final form. The slick container could be seen if user hovers a button.
Everything works great if users hover the button after the page is completely loaded because my width settings are taken into account, but if user hovers the button before that, the slick design will be broken because my width settings are overriden by slick's one.

I've debugged the problem and it seems that in the $(window).load(function() {} the slick container looks ok, the width of the slick-slides is the one I set, but when the debugger leaves the .load method, slicks overrides my widths.

My currently solution is to setTimeout of 2 seconds and then set the width of the slick-slides.

I would like to know how to fix this in a smarter way. I thought that a method to check if slick is completely loaded would help.

Thanks

**Comment by sergx** [comment]
`  if(typeof $.fn.Slick === 'undefined'){
    document.write('<script src="js/slick.min.js">\x3C/script>');
    document.write('<link href="css/slick.css" rel="stylesheet">');
    document.write('<link href="css/slick-theme.css" rel="stylesheet">');
  }`

**Comment by dnordby** [comment]
My use-case for this is an embedded app: I've built an app that on load does not display a slider. So by the time I route to a component that has a slider, `slick.js.min` is already loaded in. Great, no problems! However, the app is light enough that if a user was to refresh that route, my app reloads faster than `slick.js.min`. A callback to say "slick is loaded now!" would allow me to test (and re-test as needed) for if slick was done loading, and then execute my slider. As it stands, I just get the fun "TypeError: e(...).slick is not a function" which is sad.

**Comment by JefferyHus** [comment]
@dnordby All you have to do (which is not recommended but works). Create an interval and set your function to keep looking for slick existence in your document.

```javascript
function testimonialsSlick() {
    if (typeof $.fn.slick == 'function') {
      // do your work here
     ...
     // clear the interval
     window.clearInterval(slickInterval)
   }
}
var slickInterval = window.setInterval(testimonialsSlick, 300);
```

You can customize it as much as you want to make sure the interval won't run forever and stack the memory of your visitors. Another recommended solution is to use RequireJS.

**Comment by dnordby** [comment]
@JefferyHus this is of course what I wound up doing...I liked having the app so lightweight that I decided not to use another library just to implement a simple listener I could write myself. Just kind of too bad there’s not (currently! 🤞🏻) built in support for this.
