### ISSUE TITLE
ipad issue

### ISSUE THREAD

**Issue by salunet** [kenwheeler/slick#929]
![downloadattachment](https://cloud.githubusercontent.com/assets/1249494/5755579/abf50e54-9ca6-11e4-87f7-6bdeef172b54.png)

On the ipad and sometimes desktop the slider breaks. It seems that it partly has to do with the issue (https://github.com/kenwheeler/slick/issues/801) that the slide-active is not working. Sometimes the slider works well on the iPad but the infinite option does not work .

**Comment by simeydotme** [comment]
"__the__" iPad? 

hey @salunet thanks for contributing :smile:, but there are very very many iPads and versions of iOS running on them, please could you narrow down your scenario and also [create a JSFiddle](http://jsfiddle.net/L0hntr35/) so that we may see the bug occurring outside of your development environment? :grin: 

~ Appreciatively, Simon.

**Comment by kenwheeler** [comment]
Closing until fiddle
