### ISSUE TITLE
Slick JS not loading properly on Web Hosting

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [kenwheeler/slick#933]
Hello there,

My webpage is loading fine in local 
http://i.imgur.com/mV2N5Kg.jpg

But when I upload it on my webhost, as soon as I load the page, that happens
http://i.imgur.com/wcXc6Q3.jpg

It stays like that until I click the left/right arrow or until the autoplay starts cycling through the images...
( After that it works fine! )

Is it a problem with my webhosting ? Did I do something wrong ? (All my ressources are loaded locally on the local hosting and the web hosting)

Edit : It happens on Chrome but not for my friend who uses Firefox.

Best Regards.

**Comment by simeydotme** [comment]
@Sakarias-Longhorn - thanks for stopping by! :smile: Unfortunately this isn't really the place to get support for your project; it's for reporting bugs with the carousel plugin. I appreciate that this _could possibly_ be a bug with Slick but we need much more information and a replicable proof (in www.jsfiddle.net, preferably) to help us determine the bug. - However in this case I think it is not a bug because you've demonstrated the plugin works fine locally.

www.stackoverflow.com is a great place to get support on your own projects and if you create a topic there please come back and leave a link for me and others and we'll do our best to help you out on stackoverflow :wink: 

Simon.
