### ISSUE TITLE
Dynamically changing color of arrows based on background

### ISSUE THREAD

**Issue by akiran** [kenwheeler/slick#935]
As of now default color of arrow is white.
```scss
$slick-arrow-color: white !default;
```
If someone is trying slick for the first time and if the background is white they will not be able to see arrows.

Can we dynamically change the arrow color based on background with javascript i.e if background is dark arrows will be bright and vice-versa. ?

We can also provide an option to override color.

**Comment by simeydotme** [comment]
I would love to see the code to detect the `background-color` hahahahahaha.. :joy: - seems like a very bad idea for performance.

I think anyone with half a brain will realise why they cannot see the arrows had they even glanced at the demo/docs page :smile:

**Comment by akiran** [comment]
This demo even went a step ahead and dynamically changing arrow color based on image color.
http://www.kennethcachia.com/background-check/slider.html

I am not proposing we should do that.
I thought it is an interesting usecase relevant to this discussion.

**Comment by akiran** [comment]
There are some interesting tricks we can do with sass to dynamically change color.
http://thesassway.com/intermediate/dynamically-change-text-color-based-on-its-background-with-sass

But this project need to support pure css version also. So this may not be applicable

**Comment by simeydotme** [comment]
:) I admire your desire to help the developers, Akiran :+1: 
That plugin you show for changing the arrow color is almost 900 lines of code unminified :cry: - it would pretty much double the weight of Slick. - also Slick's arrows by default are outside of the slider.

Generally detecting the color of the space behind an element is incredibly difficult without taking a screenshot (`<canvas>`) purely because there could be a thousand parents and absolutely positioned elements behind that element.

Again, the sass solution is useful for elements inside a parent with an explicit BG color, if it's the parent's parent's parent or an absolutely position element it's completely useless :cry: 

Very sorry!
Simon.

**Comment by kenwheeler** [comment]
I dont think this functionality merits inclusion in the core codebase.
