### ISSUE TITLE
Wrong scroll direction for slickGoTo

### ISSUE THREAD

**Issue by psren** [kenwheeler/slick#960]
I have a carousel which shows 3 items and slides 1 item.
**infinite is set to true**

So i expect to scroll throught the slider by clicking the slides at the sides without a bigger jump.
Each click moves by 1 slide correctly until i reach the first slide. I click on it and it jumps the whole way back.

This is possibly related to #729 

### Way 1

Always click the right slide until you reach the first slide

### Way 2

Click on Slide 7 after the page loaded

## Isolated Test

http://jsfiddle.net/z9kdg265/5/

**Comment by simeydotme** [comment]
Hey, Actually I think you're right there should be a calculation that means the carousel always takes the "shortest distance" to the `.slickGoTo()` target; when it is in `infinite` mode.

However for your demo purposes I have provided a solution for now...

http://jsfiddle.net/h98y379z/

```js
var $c = $('.carousel');

$c.slick({
    centerMode: true,
    slidesToShow: 3,
    slidesToScroll: 1,
    infinite: true,
    centerPadding: '0px'
});

$('.carousel__item').click(function() {
    
    var $cSlick = $c.getSlick();
    var index = $(this).data("index");
    var current = $c.slickCurrentSlide();
    var last = $cSlick.slideCount - 1;

    if( current === 0 && index === last ) {
        $c.slickGoTo(-1);
    } else if ( current === last && index === 0 ) {
        $c.slickGoTo( last + 1 );
    } else {
        $c.slickGoTo(index);
    }

});
```

**Comment by kenwheeler** [comment]
Check this fiddle. You were a) using 1.3.13 and b) using your own indexes. Slick has indexes built in:

http://jsfiddle.net/k70vendr/

**Comment by rosivanov** [comment]
Hi all! I use slick 1.6.0 and the issue still exists there. Can someone advise, can this feature (scroll in "short direction") be implemented in future releases?

**Comment by vesper8** [comment]
after wasting an hour trying to make this work perfect.. the final solution is to just disable the scroll animation only when going across the bridge (from index 0,1,2,3 -> index last, last-1, last-2, last-3) or vice versa. A simplified version which works fine for me is: `slick.slickGoTo(destinationIndex, (destinationIndex > currentIndex && destinationIndex - currentIndex > 7) || (currentIndex > destinationIndex && currentIndex - destinationIndex > 7))`

This way the animation will still occur in all cases except those that would otherwise cause the animation to go crazy and go all the way around instead of stepping a few short steps like it (ideally) should

**Comment by MarkB700** [comment]
> after wasting an hour trying to make this work perfect.. the final solution is to just disable the scroll animation only when going across the bridge (from index 0,1,2,3 -> index last, last-1, last-2, last-3) or vice versa. A simplified version which works fine for me is: `slick.slickGoTo(destinationIndex, (destinationIndex > currentIndex && destinationIndex - currentIndex > 7) || (currentIndex > destinationIndex && currentIndex - destinationIndex > 7))`
> 
> This way the animation will still occur in all cases except those that would otherwise cause the animation to go crazy and go all the way around instead of stepping a few short steps like it (ideally) should

I did your method after a number of hours in it. I then ended up using something like the following using multiple slickPrev or slickNext instead of slickGoTo. The calls had to wait till the single animations finished else they didn't work.

https://jsfiddle.net/ypctqeur/3/

E.g.

function fJPrevious() {
  $('.single-item').slick('slickPrev');
  setTimeout(function() {
    $('.single-item').slick('slickPrev');
  }, 510);
  setTimeout(function() {
    $('.single-item').slick('slickPrev');
  }, 1020);
}

Naturally you could loop it n times etc. So long as you incremented the timeout milliseconds too.
