### ISSUE TITLE
Move carousel only in drag direction

### ISSUE THREAD

**Issue by badbojo** [kenwheeler/slick#978]
hi again
Feature request:
Move carousel only in the direction you drag without shifting back.

In this case I expecting to see 5th slide, but carousel moving back:
http://gyazo.com/73722670c2e06a41b992f80f28a94b00

**Comment by kenwheeler** [comment]
Ok this is the 3rd and last time I'm going to say this. Stop posting your videos, and opening up bunk issues. Go read contributing.markdown, follow the guidelines, and then I'll review this. The carousel is moving back because its slidesToScroll: 4. You haven't scrolled enough to constitute a full swipe.

**Comment by badbojo** [comment]
I'm sorry to interrupt you, but that's exactly what I mean. In this case, I expect that the carousel will move forward on 4 slides.

>The carousel is moving back because its slidesToScroll: 4. You haven't scrolled enough to constitute a full swipe.

How to set up a carousel that it was moving forward in this case?

Thanks.

**Comment by kenwheeler** [comment]
You would need to swipe farther or use the swipeToSlide option

**Comment by badbojo** [comment]
Will use Jsfiddle next time.
Thanks a lot!
